"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdjustmentReversalDetails = void 0;
var AdjustmentReversalDetails = /** @class */ (function () {
    function AdjustmentReversalDetails() {
    }
    AdjustmentReversalDetails.getAttributeTypeMap = function () {
        return AdjustmentReversalDetails.attributeTypeMap;
    };
    AdjustmentReversalDetails.discriminator = undefined;
    AdjustmentReversalDetails.attributeTypeMap = [
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "string"
        },
        {
            "name": "eventExpiryDateTime",
            "baseName": "eventExpiryDateTime",
            "type": "string"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "eventReferenceId",
            "baseName": "eventReferenceId",
            "type": "string"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string"
        },
        {
            "name": "replacementAmount",
            "baseName": "replacementAmount",
            "type": "AmountDetails"
        },
        {
            "name": "reasonCode",
            "baseName": "reasonCode",
            "type": "string"
        },
        {
            "name": "controlNumber",
            "baseName": "controlNumber",
            "type": "string"
        },
        {
            "name": "clearingStatus",
            "baseName": "clearingStatus",
            "type": "string"
        },
        {
            "name": "rejectCode",
            "baseName": "rejectCode",
            "type": "string"
        },
        {
            "name": "rejectReason",
            "baseName": "rejectReason",
            "type": "string"
        },
        {
            "name": "settlementDate",
            "baseName": "settlementDate",
            "type": "string"
        },
        {
            "name": "issuerSettlementAmount",
            "baseName": "issuerSettlementAmount",
            "type": "AmountDetails"
        },
        {
            "name": "issuerSettlementAmountIndicator",
            "baseName": "issuerSettlementAmountIndicator",
            "type": "string"
        },
        {
            "name": "acquirerSettlementAmount",
            "baseName": "acquirerSettlementAmount",
            "type": "AmountDetails"
        },
        {
            "name": "acquirerSettlementAmountIndicator",
            "baseName": "acquirerSettlementAmountIndicator",
            "type": "string"
        },
        {
            "name": "creationDate",
            "baseName": "creationDate",
            "type": "string"
        },
        {
            "name": "eventLastModifiedBy",
            "baseName": "eventLastModifiedBy",
            "type": "string"
        },
        {
            "name": "lastUpdatedDateTime",
            "baseName": "lastUpdatedDateTime",
            "type": "string"
        }
    ];
    return AdjustmentReversalDetails;
}());
exports.AdjustmentReversalDetails = AdjustmentReversalDetails;
