"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CardholderVerificationMethodStructure = void 0;
var CardholderVerificationMethodStructure = /** @class */ (function () {
    function CardholderVerificationMethodStructure() {
    }
    CardholderVerificationMethodStructure.getAttributeTypeMap = function () {
        return CardholderVerificationMethodStructure.attributeTypeMap;
    };
    CardholderVerificationMethodStructure.discriminator = undefined;
    CardholderVerificationMethodStructure.attributeTypeMap = [
        {
            "name": "onlinePIN",
            "baseName": "onlinePIN",
            "type": "string"
        },
        {
            "name": "offlinePIN",
            "baseName": "offlinePIN",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "none",
            "baseName": "none",
            "type": "string"
        }
    ];
    return CardholderVerificationMethodStructure;
}());
exports.CardholderVerificationMethodStructure = CardholderVerificationMethodStructure;
