/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CaseFilingDetails {
    /**
    * Claim identifier associated with the standard claimId
    */
    'claimId'?: string;
    /**
    * Claim Type
    */
    'claimType'?: string;
    /**
    * Identifier assigned to the case filing
    */
    'caseId'?: string;
    /**
    * Type of Case Filing. The following number values represent each case type.  1-Pre-arbitration  2-Arbitration  3-Pre-compliance 4-Compliance
    */
    'caseType'?: string;
    /**
    * A list of Chargeback Reference numbers
    */
    'chargebackRefNum'?: Array<string>;
    /**
    * The case currency. Value should be standard alpha currency code.   For domestic transactions: domestic currency or USD   For cross-border transactions: USD or EUR, per Global Clearing Management System rules   Length: 3   Valid values/format: USD, EUR, GBP, MXN etc and A-Z (uppercase alphabetic letter)  
    */
    'currencyCode'?: string;
    /**
    * Customer filing number which is the filing party\'s internal number
    */
    'customerFilingNumber'?: string;
    /**
    * Credit date when the violationCode is 1.4 in the case of pre-compliance or compliance case filing. The format should be yyyy-MM-dd
    */
    'creditDate'?: string;
    /**
    * Chargeback date when the violationCode is 1.4 in the case of pre-compliance or compliance case filing. The format should be yyyy-MM-dd
    */
    'chargebackDate'?: string;
    /**
    * Reason code is returned when the case type is pre-arbitration or arbitration.
    */
    'reasonCode'?: string;
    /**
    * Dispute amount.  The currency will be determined by the ICA region entered in the Filed ICA and Filed Against ICA
    */
    'disputeAmount'?: string;
    /**
    * Due date when the response is required.  The format should be yyyy-MM-dd
    */
    'dueDate'?: string;
    /**
    * Filed Against ICA
    */
    'filingAgaintstIca'?: string;
    /**
    * Filing case as Issuer or Acquirer. Following values represents each type I-ISSUER  A-ACQUIRER
    */
    'filingAs'?: string;
    /**
    * Filing ICA
    */
    'filingIca'?: string;
    /**
    * Merchant name for filing pre-arbitration and arbitration case
    */
    'merchantName'?: string;
    /**
    * The primary account number
    */
    'primaryAccountNum'?: string;
    /**
    * Violation code
    */
    'violationCode'?: string;
    /**
    * Violation Date
    */
    'violationDate'?: string;
    /**
    * Ruling Date
    */
    'rulingDate'?: string;
    /**
    * Ruling Status.  Valid values are Reviewed, Filed In Error, Declined, Expired, Favor Sender, Favor Receiver
    */
    'rulingStatus'?: string;
    /**
    * The virtual account number
    */
    'virtualAccountNum'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "claimId",
            "baseName": "claimId",
            "type": "string"
        },
        {
            "name": "claimType",
            "baseName": "claimType",
            "type": "string"
        },
        {
            "name": "caseId",
            "baseName": "caseId",
            "type": "string"
        },
        {
            "name": "caseType",
            "baseName": "caseType",
            "type": "string"
        },
        {
            "name": "chargebackRefNum",
            "baseName": "chargebackRefNum",
            "type": "Array<string>"
        },
        {
            "name": "currencyCode",
            "baseName": "currencyCode",
            "type": "string"
        },
        {
            "name": "customerFilingNumber",
            "baseName": "customerFilingNumber",
            "type": "string"
        },
        {
            "name": "creditDate",
            "baseName": "creditDate",
            "type": "string"
        },
        {
            "name": "chargebackDate",
            "baseName": "chargebackDate",
            "type": "string"
        },
        {
            "name": "reasonCode",
            "baseName": "reasonCode",
            "type": "string"
        },
        {
            "name": "disputeAmount",
            "baseName": "disputeAmount",
            "type": "string"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string"
        },
        {
            "name": "filingAgaintstIca",
            "baseName": "filingAgaintstIca",
            "type": "string"
        },
        {
            "name": "filingAs",
            "baseName": "filingAs",
            "type": "string"
        },
        {
            "name": "filingIca",
            "baseName": "filingIca",
            "type": "string"
        },
        {
            "name": "merchantName",
            "baseName": "merchantName",
            "type": "string"
        },
        {
            "name": "primaryAccountNum",
            "baseName": "primaryAccountNum",
            "type": "string"
        },
        {
            "name": "violationCode",
            "baseName": "violationCode",
            "type": "string"
        },
        {
            "name": "violationDate",
            "baseName": "violationDate",
            "type": "string"
        },
        {
            "name": "rulingDate",
            "baseName": "rulingDate",
            "type": "string"
        },
        {
            "name": "rulingStatus",
            "baseName": "rulingStatus",
            "type": "string"
        },
        {
            "name": "virtualAccountNum",
            "baseName": "virtualAccountNum",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CaseFilingDetails.attributeTypeMap;
    }
}

