/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CaseFilingImageStatusResponseStructure {
    /**
    * Case Id
    */
    'caseId'?: string;
    /**
    * Status of case filing images, the valid values are: COMPLETED, FAILED, UNPROCESSED.COMPLETED: Image was processed and no further action required. FAILED: Some failure happened during image process flow, i.e,The image could not be converted, The image is not imported, Image extension not supported etc.UNPROCESSED: The image is unavailable because it is not picked up by mastercom internal processes yet.
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caseId",
            "baseName": "caseId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CaseFilingImageStatusResponseStructure.attributeTypeMap;
    }
}

