/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargebackImageStatusResponseStructure } from './chargebackImageStatusResponseStructure';

export class ChargebackImageStatusResponse {
    /**
    * A list of chargeback image statuses
    */
    'chargebackImageStatusList'?: Array<ChargebackImageStatusResponseStructure>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chargebackImageStatusList",
            "baseName": "chargebackImageStatusList",
            "type": "Array<ChargebackImageStatusResponseStructure>"
        }    ];

    static getAttributeTypeMap() {
        return ChargebackImageStatusResponse.attributeTypeMap;
    }
}

