"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClaimCollaborationDetails = void 0;
/**
* Root element for a list of collaboration details.
*/
var ClaimCollaborationDetails = /** @class */ (function () {
    function ClaimCollaborationDetails() {
    }
    ClaimCollaborationDetails.getAttributeTypeMap = function () {
        return ClaimCollaborationDetails.attributeTypeMap;
    };
    ClaimCollaborationDetails.discriminator = undefined;
    ClaimCollaborationDetails.attributeTypeMap = [
        {
            "name": "collaborationAmount",
            "baseName": "collaborationAmount",
            "type": "AmountDetails"
        },
        {
            "name": "reasonCode",
            "baseName": "reasonCode",
            "type": "string"
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string"
        },
        {
            "name": "responseCode",
            "baseName": "responseCode",
            "type": "string"
        },
        {
            "name": "eventReferenceId",
            "baseName": "eventReferenceId",
            "type": "string"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "string"
        },
        {
            "name": "eventStatus",
            "baseName": "eventStatus",
            "type": "string"
        },
        {
            "name": "creationDate",
            "baseName": "creationDate",
            "type": "string"
        },
        {
            "name": "eventExpiryDateTime",
            "baseName": "eventExpiryDateTime",
            "type": "string"
        },
        {
            "name": "ownerUserId",
            "baseName": "ownerUserId",
            "type": "string"
        },
        {
            "name": "refundReversalType",
            "baseName": "refundReversalType",
            "type": "string"
        },
        {
            "name": "refundReversalAmount",
            "baseName": "refundReversalAmount",
            "type": "AmountDetails"
        },
        {
            "name": "refundReversalDateTime",
            "baseName": "refundReversalDateTime",
            "type": "string"
        },
        {
            "name": "refundReversalReferenceId",
            "baseName": "refundReversalReferenceId",
            "type": "string"
        },
        {
            "name": "eventLastModifiedBy",
            "baseName": "eventLastModifiedBy",
            "type": "string"
        },
        {
            "name": "lastUpdatedDateTime",
            "baseName": "lastUpdatedDateTime",
            "type": "string"
        },
        {
            "name": "documentIndicator",
            "baseName": "documentIndicator",
            "type": "string"
        },
        {
            "name": "documentStatus",
            "baseName": "documentStatus",
            "type": "string"
        },
        {
            "name": "completedDocumentsAttributes",
            "baseName": "completedDocumentsAttributes",
            "type": "Array<CompletedDocumentAttributes>"
        }
    ];
    return ClaimCollaborationDetails;
}());
exports.ClaimCollaborationDetails = ClaimCollaborationDetails;
