"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateRetrievalRequestSingle = void 0;
var CreateRetrievalRequestSingle = /** @class */ (function () {
    function CreateRetrievalRequestSingle() {
    }
    CreateRetrievalRequestSingle.getAttributeTypeMap = function () {
        return CreateRetrievalRequestSingle.attributeTypeMap;
    };
    CreateRetrievalRequestSingle.discriminator = undefined;
    CreateRetrievalRequestSingle.attributeTypeMap = [
        {
            "name": "documentType",
            "baseName": "documentType",
            "type": "CreateRetrievalRequestSingle.DocumentTypeEnum"
        },
        {
            "name": "replacementAmount",
            "baseName": "replacementAmount",
            "type": "string"
        },
        {
            "name": "reversalReasonCode",
            "baseName": "reversalReasonCode",
            "type": "string"
        },
        {
            "name": "usageCode",
            "baseName": "usageCode",
            "type": "CreateRetrievalRequestSingle.UsageCodeEnum"
        },
        {
            "name": "additionalInformation",
            "baseName": "additionalInformation",
            "type": "string"
        },
        {
            "name": "controlNumber",
            "baseName": "controlNumber",
            "type": "string"
        }
    ];
    return CreateRetrievalRequestSingle;
}());
exports.CreateRetrievalRequestSingle = CreateRetrievalRequestSingle;
(function (CreateRetrievalRequestSingle) {
    var DocumentTypeEnum;
    (function (DocumentTypeEnum) {
        DocumentTypeEnum[DocumentTypeEnum["_2"] = '2'] = "_2";
        DocumentTypeEnum[DocumentTypeEnum["_4"] = '4'] = "_4";
    })(DocumentTypeEnum = CreateRetrievalRequestSingle.DocumentTypeEnum || (CreateRetrievalRequestSingle.DocumentTypeEnum = {}));
    var UsageCodeEnum;
    (function (UsageCodeEnum) {
        UsageCodeEnum[UsageCodeEnum["_1"] = '1'] = "_1";
        UsageCodeEnum[UsageCodeEnum["_2"] = '2'] = "_2";
        UsageCodeEnum[UsageCodeEnum["_3"] = '3'] = "_3";
        UsageCodeEnum[UsageCodeEnum["_6"] = '6'] = "_6";
        UsageCodeEnum[UsageCodeEnum["_7"] = '7'] = "_7";
    })(UsageCodeEnum = CreateRetrievalRequestSingle.UsageCodeEnum || (CreateRetrievalRequestSingle.UsageCodeEnum = {}));
})(CreateRetrievalRequestSingle || (exports.CreateRetrievalRequestSingle = CreateRetrievalRequestSingle = {}));
