/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CaseFilingEbdfStructure } from './caseFilingEbdfStructure';
import { DocumentStructure } from './documentStructure';

export class CreateCaseRequest {
    /**
    * Type of Case Filing.   Length: 1   Valid Values/Format: 1-Pre-arbitration, 2-Arbitration, 3-Pre-compliance, 4-Compliance
    */
    'caseType': CreateCaseRequest.CaseTypeEnum;
    /**
    * A list of Chargeback Reference numbers.   CONDITIONAL: This field is mandatory and applicable if the case type is pre-arbitration or arbitration or if the primary account number field is not populated.   Pre-Arbitration and Arbitration case will have one chargeback to one case filing. Pre-Compliance and Compliance case can have many chargeback to one case filing.   Length: 0-10   Valid Values/Format: Numeric
    */
    'chargebackRefNum'?: Array<string>;
    /**
    * Customer filing number which is the filing party\'s internal number.   Length: 0-15   Valid Values/Format: Numeric
    */
    'customerFilingNumber'?: string;
    /**
    * Dispute amount. The currency will be determined by the ICA region entered in the Filed ICA and Filed Against ICA.   Length: 1-10 (Integer Part). 2 (Decimal Part)   Valid Values/Format: Decimal
    */
    'disputeAmount': string;
    /**
    * The case currency. Value should be standard alpha currency code.   For domestic transactions: domestic currency or USD   For cross-border transactions: USD or EUR, per Global Clearing Management System rules   Length: 3   Valid values/format: USD, EUR, GBP, MXN etc and A-Z (uppercase alphabetic letter)  
    */
    'currencyCode': string;
    /**
    * Due date when the response is required.   Length: 10   Valid Values/Format: Date (yyyy-MM-dd)
    */
    'dueDate'?: string;
    'fileAttachment'?: DocumentStructure;
    /**
    * Filed Against ICA.   Length: 1-11   Valid Values/Format: Numeric
    */
    'filedAgainstIca': string;
    /**
    * Filing case as Issuer or Acquirer.   Length: 1   Valid Values/Format: I, A
    */
    'filingAs': CreateCaseRequest.FilingAsEnum;
    /**
    * Filing ICA.   Length: 1-11   Valid Values/Format: Numeric
    */
    'filingIca': string;
    /**
    * Enter a Memo pertaining to the case.   Length: 1-13000   Valid Values/Format: Alphanumeric and Special Characters (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'memo': string;
    /**
    * Enter a MessageText pertaining to the case.   CONDITIONAL: Applicable only for filing pre-arbitration and arbitration case for sender while creating the case.   Length: 1-100   Valid Values/Format: Alphanumeric and Special Characters (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'messageText'?: string;
    /**
    * Change reason code Flag.   CONDITIONAL: Applicable only for filing pre-arbitration and arbitration case for sender while creating the case.   Length: 1   Valid Values/Format: Y,N
    */
    'changeReasonCodeFlag'?: string;
    /**
    * Updated Chargeback Reason Code.   CONDITIONAL: Required and applicable for filing pre-arbitration and arbitration case for sender while creating the case and if changeReasonCodeFlag is Y.   Length: 2-4   Valid Values/Format: 4863,4899,2001,2002,2003,2004,2005,2008,2011,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,4801,4802,4807,4808,4809,4812,4831,4834,4835,4837,4840,4841,4842,4846,4847,4849,4850,4853,4854,4855,4856,4857,4859,4860,4862,4900,4901,4902,4903,4905,4908,2000,4870,4871,03,06,17,30,69,70,71,73,74,75,79,80,82,85,95,96,97,98,13,10,20,24,25,26,27,28,29
    */
    'updatedChargebackReasonCode'?: CreateCaseRequest.UpdatedChargebackReasonCodeEnum;
    /**
    * Change reason Code reason.   CONDITIONAL: Required and applicable for filing pre-arbitration and arbitration case for sender while creating the case and if changeReasonCodeFlag is Y.   Length: 1-1000   Valid Values/Format: Alphanumeric and Special Characters (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'changeReasonCodeReason'?: string;
    /**
    * The primary account number.   CONDITIONAL: This field is mandatory and applicable if the chargeback ref number field is not populated.   Length: 1-19   Valid Values/Format: Numeric
    */
    'primaryAccountNum'?: string;
    /**
    * The acquirer reference number.   CONDITIONAL: This field is mandatory and applicable if case is created using primary account number.   Length: 1-23   Valid Values/Format: Numeric
    */
    'acquirerRefNum'?: string;
    /**
    * Chargeback Reason Code.   CONDITIONAL: Required and applicable for filing pre-arbitration and arbitration case.   Length: 2-4   Valid Values/Format: 4863,4899,2001,2002,2003,2004,2005,2008,2011,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,4801,4802,4807,4808,4809,4812,4831,4834,4835,4837,4840,4841,4842,4846,4847,4849,4850,4853,4854,4855,4856,4857,4859,4860,4862,4900,4901,4902,4903,4905,4908,2000,4870,4871,03,06,17,30,69,70,71,73,74,75,79,80,82,85,95,96,97,98,13,10,20,24,25,26,27,28,29
    */
    'chargebackReasonCode'?: CreateCaseRequest.ChargebackReasonCodeEnum;
    /**
    * Merchant name.   CONDITIONAL: This is required and applicable for filing pre-arbitration and arbitration case.   Length: 0-100   Valid Values/Format: Alphanumeric and Special Characters (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'merchantName'?: string;
    /**
    * Violation code.   CONDITIONAL: This is only applicable and mandatory in case of pre-compliance and compliance types of cases   Length: 1-20   Valid Values/Format: Alphanumeric and Special Character (.)
    */
    'violationCode'?: string;
    /**
    * Violation Date.   CONDITIONAL: This is only applicable and mandatory in case of pre-compliance and compliance types of cases.   Length: 10   Valid Values/Format: Date (yyyy-MM-dd)
    */
    'violationDate'?: string;
    /**
    * Chargeback Date.   CONDITIONAL:  This is only applicable and mandatory in case of pre-compliance and compliance types of cases with a violation code of 1.4.   Length: 10   Valid Values/Format: Date (yyyy-MM-dd)
    */
    'chargebackDate'?: string;
    /**
    * Credit Date.   CONDITIONAL:  This is only applicable and mandatory in case of pre-compliance and compliance types of cases with a violation code of 1.4.   Length: 10   Valid Values/Format: Date (yyyy-MM-dd)
    */
    'creditDate'?: string;
    'caseFilingEbdfDocuments'?: CaseFilingEbdfStructure;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caseType",
            "baseName": "caseType",
            "type": "CreateCaseRequest.CaseTypeEnum"
        },
        {
            "name": "chargebackRefNum",
            "baseName": "chargebackRefNum",
            "type": "Array<string>"
        },
        {
            "name": "customerFilingNumber",
            "baseName": "customerFilingNumber",
            "type": "string"
        },
        {
            "name": "disputeAmount",
            "baseName": "disputeAmount",
            "type": "string"
        },
        {
            "name": "currencyCode",
            "baseName": "currencyCode",
            "type": "string"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "string"
        },
        {
            "name": "fileAttachment",
            "baseName": "fileAttachment",
            "type": "DocumentStructure"
        },
        {
            "name": "filedAgainstIca",
            "baseName": "filedAgainstIca",
            "type": "string"
        },
        {
            "name": "filingAs",
            "baseName": "filingAs",
            "type": "CreateCaseRequest.FilingAsEnum"
        },
        {
            "name": "filingIca",
            "baseName": "filingIca",
            "type": "string"
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string"
        },
        {
            "name": "messageText",
            "baseName": "messageText",
            "type": "string"
        },
        {
            "name": "changeReasonCodeFlag",
            "baseName": "changeReasonCodeFlag",
            "type": "string"
        },
        {
            "name": "updatedChargebackReasonCode",
            "baseName": "updatedChargebackReasonCode",
            "type": "CreateCaseRequest.UpdatedChargebackReasonCodeEnum"
        },
        {
            "name": "changeReasonCodeReason",
            "baseName": "changeReasonCodeReason",
            "type": "string"
        },
        {
            "name": "primaryAccountNum",
            "baseName": "primaryAccountNum",
            "type": "string"
        },
        {
            "name": "acquirerRefNum",
            "baseName": "acquirerRefNum",
            "type": "string"
        },
        {
            "name": "chargebackReasonCode",
            "baseName": "chargebackReasonCode",
            "type": "CreateCaseRequest.ChargebackReasonCodeEnum"
        },
        {
            "name": "merchantName",
            "baseName": "merchantName",
            "type": "string"
        },
        {
            "name": "violationCode",
            "baseName": "violationCode",
            "type": "string"
        },
        {
            "name": "violationDate",
            "baseName": "violationDate",
            "type": "string"
        },
        {
            "name": "chargebackDate",
            "baseName": "chargebackDate",
            "type": "string"
        },
        {
            "name": "creditDate",
            "baseName": "creditDate",
            "type": "string"
        },
        {
            "name": "caseFilingEbdfDocuments",
            "baseName": "caseFilingEbdfDocuments",
            "type": "CaseFilingEbdfStructure"
        }    ];

    static getAttributeTypeMap() {
        return CreateCaseRequest.attributeTypeMap;
    }
}

export namespace CreateCaseRequest {
    export enum CaseTypeEnum {
        _1 = <any> '1',
        _2 = <any> '2',
        _3 = <any> '3',
        _4 = <any> '4'
    }
    export enum FilingAsEnum {
        I = <any> 'I',
        A = <any> 'A'
    }
    export enum UpdatedChargebackReasonCodeEnum {
        _4863 = <any> '4863',
        _4899 = <any> '4899',
        _2001 = <any> '2001',
        _2002 = <any> '2002',
        _2003 = <any> '2003',
        _2004 = <any> '2004',
        _2005 = <any> '2005',
        _2008 = <any> '2008',
        _2011 = <any> '2011',
        _2700 = <any> '2700',
        _2701 = <any> '2701',
        _2702 = <any> '2702',
        _2703 = <any> '2703',
        _2704 = <any> '2704',
        _2705 = <any> '2705',
        _2706 = <any> '2706',
        _2707 = <any> '2707',
        _2708 = <any> '2708',
        _2709 = <any> '2709',
        _2710 = <any> '2710',
        _2711 = <any> '2711',
        _2712 = <any> '2712',
        _2713 = <any> '2713',
        _4801 = <any> '4801',
        _4802 = <any> '4802',
        _4807 = <any> '4807',
        _4808 = <any> '4808',
        _4809 = <any> '4809',
        _4812 = <any> '4812',
        _4831 = <any> '4831',
        _4834 = <any> '4834',
        _4835 = <any> '4835',
        _4837 = <any> '4837',
        _4840 = <any> '4840',
        _4841 = <any> '4841',
        _4842 = <any> '4842',
        _4846 = <any> '4846',
        _4847 = <any> '4847',
        _4849 = <any> '4849',
        _4850 = <any> '4850',
        _4853 = <any> '4853',
        _4854 = <any> '4854',
        _4855 = <any> '4855',
        _4856 = <any> '4856',
        _4857 = <any> '4857',
        _4859 = <any> '4859',
        _4860 = <any> '4860',
        _4862 = <any> '4862',
        _4900 = <any> '4900',
        _4901 = <any> '4901',
        _4902 = <any> '4902',
        _4903 = <any> '4903',
        _4905 = <any> '4905',
        _4908 = <any> '4908',
        _2000 = <any> '2000',
        _4870 = <any> '4870',
        _4871 = <any> '4871',
        _03 = <any> '03',
        _06 = <any> '06',
        _17 = <any> '17',
        _30 = <any> '30',
        _69 = <any> '69',
        _70 = <any> '70',
        _71 = <any> '71',
        _73 = <any> '73',
        _74 = <any> '74',
        _75 = <any> '75',
        _79 = <any> '79',
        _80 = <any> '80',
        _82 = <any> '82',
        _85 = <any> '85',
        _95 = <any> '95',
        _96 = <any> '96',
        _97 = <any> '97',
        _98 = <any> '98',
        _13 = <any> '13',
        _10 = <any> '10',
        _20 = <any> '20',
        _24 = <any> '24',
        _25 = <any> '25',
        _26 = <any> '26',
        _27 = <any> '27',
        _28 = <any> '28',
        _29 = <any> '29'
    }
    export enum ChargebackReasonCodeEnum {
        _4863 = <any> '4863',
        _4899 = <any> '4899',
        _2001 = <any> '2001',
        _2002 = <any> '2002',
        _2003 = <any> '2003',
        _2004 = <any> '2004',
        _2005 = <any> '2005',
        _2008 = <any> '2008',
        _2011 = <any> '2011',
        _2700 = <any> '2700',
        _2701 = <any> '2701',
        _2702 = <any> '2702',
        _2703 = <any> '2703',
        _2704 = <any> '2704',
        _2705 = <any> '2705',
        _2706 = <any> '2706',
        _2707 = <any> '2707',
        _2708 = <any> '2708',
        _2709 = <any> '2709',
        _2710 = <any> '2710',
        _2711 = <any> '2711',
        _2712 = <any> '2712',
        _2713 = <any> '2713',
        _4801 = <any> '4801',
        _4802 = <any> '4802',
        _4807 = <any> '4807',
        _4808 = <any> '4808',
        _4809 = <any> '4809',
        _4812 = <any> '4812',
        _4831 = <any> '4831',
        _4834 = <any> '4834',
        _4835 = <any> '4835',
        _4837 = <any> '4837',
        _4840 = <any> '4840',
        _4841 = <any> '4841',
        _4842 = <any> '4842',
        _4846 = <any> '4846',
        _4847 = <any> '4847',
        _4849 = <any> '4849',
        _4850 = <any> '4850',
        _4853 = <any> '4853',
        _4854 = <any> '4854',
        _4855 = <any> '4855',
        _4856 = <any> '4856',
        _4857 = <any> '4857',
        _4859 = <any> '4859',
        _4860 = <any> '4860',
        _4862 = <any> '4862',
        _4900 = <any> '4900',
        _4901 = <any> '4901',
        _4902 = <any> '4902',
        _4903 = <any> '4903',
        _4905 = <any> '4905',
        _4908 = <any> '4908',
        _2000 = <any> '2000',
        _4870 = <any> '4870',
        _4871 = <any> '4871',
        _03 = <any> '03',
        _06 = <any> '06',
        _17 = <any> '17',
        _30 = <any> '30',
        _69 = <any> '69',
        _70 = <any> '70',
        _71 = <any> '71',
        _73 = <any> '73',
        _74 = <any> '74',
        _75 = <any> '75',
        _79 = <any> '79',
        _80 = <any> '80',
        _82 = <any> '82',
        _85 = <any> '85',
        _95 = <any> '95',
        _96 = <any> '96',
        _97 = <any> '97',
        _98 = <any> '98',
        _13 = <any> '13',
        _10 = <any> '10',
        _20 = <any> '20',
        _24 = <any> '24',
        _25 = <any> '25',
        _26 = <any> '26',
        _27 = <any> '27',
        _28 = <any> '28',
        _29 = <any> '29'
    }
}
