"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentAttributes = void 0;
var DocumentAttributes = /** @class */ (function () {
    function DocumentAttributes() {
    }
    DocumentAttributes.getAttributeTypeMap = function () {
        return DocumentAttributes.attributeTypeMap;
    };
    DocumentAttributes.discriminator = undefined;
    DocumentAttributes.attributeTypeMap = [
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "claimId",
            "baseName": "claimId",
            "type": "string"
        },
        {
            "name": "documentStatus",
            "baseName": "documentStatus",
            "type": "string"
        },
        {
            "name": "completedDocumentsAttributes",
            "baseName": "completedDocumentsAttributes",
            "type": "Array<CompletedDocumentAttributes>"
        }
    ];
    return DocumentAttributes;
}());
exports.DocumentAttributes = DocumentAttributes;
