/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExpeditedBillingDrfDocumentStructure {
    /**
    * CONDITIONAL: The cardholder\'s name is optional on Dispute Resolution Form - Pre-Compliance/Compliance form.   Length: 1-30   Valid Values/Format: Alphanumeric, Special Char (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'cardholderName'?: string;
    /**
    * The Acquirerâ€™s Reference Data.   Length: 1-23   Valid Values/Format: Numeric
    */
    'acquirerRefData'?: string;
    /**
    * The transaction date.   Length: 11   Valid Values/Format: Date (dd-MMM-yyyy)
    */
    'transactionDate'?: string;
    /**
    * The total transaction amount.   Length: 4-12   Valid Values/Format: Numeric
    */
    'transactionAmount'?: string;
    /**
    * Give a reasonably specific description of the dispute.   Length: 1-1500   Valid Values/Format: Alphanumeric, Special Char (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'disputeDescription'?: string;
    /**
    * Who is the company representative or government agency representative on behalf of the corporate card.   Length: 1-24   Valid Values/Format: Alphanumeric, Special Char (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'certification'?: string;
    /**
    * Customer Service/Chargeback Representative.   Length: 1-25   Valid Values/Format: Alphanumeric, Special Char (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'chargebackRepresentative'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cardholderName",
            "baseName": "cardholderName",
            "type": "string"
        },
        {
            "name": "acquirerRefData",
            "baseName": "acquirerRefData",
            "type": "string"
        },
        {
            "name": "transactionDate",
            "baseName": "transactionDate",
            "type": "string"
        },
        {
            "name": "transactionAmount",
            "baseName": "transactionAmount",
            "type": "string"
        },
        {
            "name": "disputeDescription",
            "baseName": "disputeDescription",
            "type": "string"
        },
        {
            "name": "certification",
            "baseName": "certification",
            "type": "string"
        },
        {
            "name": "chargebackRepresentative",
            "baseName": "chargebackRepresentative",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExpeditedBillingDrfDocumentStructure.attributeTypeMap;
    }
}

