"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FeeDetails = void 0;
var FeeDetails = /** @class */ (function () {
    function FeeDetails() {
    }
    FeeDetails.getAttributeTypeMap = function () {
        return FeeDetails.attributeTypeMap;
    };
    FeeDetails.discriminator = undefined;
    FeeDetails.attributeTypeMap = [
        {
            "name": "cardAcceptorIdCode",
            "baseName": "cardAcceptorIdCode",
            "type": "string"
        },
        {
            "name": "cardNumber",
            "baseName": "cardNumber",
            "type": "string"
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "feeDate",
            "baseName": "feeDate",
            "type": "string"
        },
        {
            "name": "destinationMember",
            "baseName": "destinationMember",
            "type": "string"
        },
        {
            "name": "feeId",
            "baseName": "feeId",
            "type": "string"
        },
        {
            "name": "feeAmount",
            "baseName": "feeAmount",
            "type": "string"
        },
        {
            "name": "creditSender",
            "baseName": "creditSender",
            "type": "boolean"
        },
        {
            "name": "creditReceiver",
            "baseName": "creditReceiver",
            "type": "boolean"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "rejectReason",
            "baseName": "rejectReason",
            "type": "string"
        },
        {
            "name": "chargebackRefNum",
            "baseName": "chargebackRefNum",
            "type": "string"
        },
        {
            "name": "reconciliationAmount",
            "baseName": "reconciliationAmount",
            "type": "string"
        },
        {
            "name": "reconciliationCurrency",
            "baseName": "reconciliationCurrency",
            "type": "string"
        },
        {
            "name": "japanCommonMerchantCode",
            "baseName": "japanCommonMerchantCode",
            "type": "string"
        },
        {
            "name": "installmentData",
            "baseName": "installmentData",
            "type": "string"
        },
        {
            "name": "flexCode",
            "baseName": "flexCode",
            "type": "string"
        }
    ];
    return FeeDetails;
}());
exports.FeeDetails = FeeDetails;
