/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardholderVerificationMethodStructure } from './cardholderVerificationMethodStructure';

export class FraudDrfDocumentStructure {
    /**
    * Numeric value of number of transactions being disputed.   Length: 0-19   Valid Values/Format: Numeric
    */
    'numberOfItems'?: string;
    /**
    * Enter any of the valid values comma separated.   Length: 7-12   Valid Values/Format: CARD_CLOSED, REPORT_SAFE, CAPTURE_CARD, LOST_STOLEN, COUNTERFEIT, RC_4837, RC_4840
    */
    'types'?: string;
    /**
    * Additional information, if needed   Length: 0-1000   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'additionalInformation'?: string;
    /**
    * Customer Service/Chargeback Representative   Length: 0-25   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&*()_+{}|:\"<>?,./;\'[]-=)
    */
    'chargebackRepresentative'?: string;
    /**
    * The card issuer region.   Length: 2-6   Valid Values/Format: AP, Europe, NAM, LAC, MEA
    */
    'cardIssuerRegion'?: FraudDrfDocumentStructure.CardIssuerRegionEnum;
    'cardholderVerificationMethod'?: CardholderVerificationMethodStructure;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfItems",
            "baseName": "numberOfItems",
            "type": "string"
        },
        {
            "name": "types",
            "baseName": "types",
            "type": "string"
        },
        {
            "name": "additionalInformation",
            "baseName": "additionalInformation",
            "type": "string"
        },
        {
            "name": "chargebackRepresentative",
            "baseName": "chargebackRepresentative",
            "type": "string"
        },
        {
            "name": "cardIssuerRegion",
            "baseName": "cardIssuerRegion",
            "type": "FraudDrfDocumentStructure.CardIssuerRegionEnum"
        },
        {
            "name": "cardholderVerificationMethod",
            "baseName": "cardholderVerificationMethod",
            "type": "CardholderVerificationMethodStructure"
        }    ];

    static getAttributeTypeMap() {
        return FraudDrfDocumentStructure.attributeTypeMap;
    }
}

export namespace FraudDrfDocumentStructure {
    export enum CardIssuerRegionEnum {
        Ap = <any> 'AP',
        Europe = <any> 'Europe',
        Nam = <any> 'NAM',
        Lac = <any> 'LAC',
        Mea = <any> 'MEA'
    }
}
