"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetQueueContentRequest = void 0;
var GetQueueContentRequest = /** @class */ (function () {
    function GetQueueContentRequest() {
    }
    GetQueueContentRequest.getAttributeTypeMap = function () {
        return GetQueueContentRequest.attributeTypeMap;
    };
    GetQueueContentRequest.discriminator = undefined;
    GetQueueContentRequest.attributeTypeMap = [
        {
            "name": "queueName",
            "baseName": "queueName",
            "type": "string"
        },
        {
            "name": "lastModifiedDateFrom",
            "baseName": "lastModifiedDateFrom",
            "type": "string"
        },
        {
            "name": "lastModifiedDateTo",
            "baseName": "lastModifiedDateTo",
            "type": "string"
        },
        {
            "name": "pageNb",
            "baseName": "pageNb",
            "type": "string"
        }
    ];
    return GetQueueContentRequest;
}());
exports.GetQueueContentRequest = GetQueueContentRequest;
