"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InstallmentParameters = void 0;
var InstallmentParameters = /** @class */ (function () {
    function InstallmentParameters() {
    }
    InstallmentParameters.getAttributeTypeMap = function () {
        return InstallmentParameters.attributeTypeMap;
    };
    InstallmentParameters.discriminator = undefined;
    InstallmentParameters.attributeTypeMap = [
        {
            "name": "deferredGracePeriodFlag",
            "baseName": "deferredGracePeriodFlag",
            "type": "string"
        },
        {
            "name": "deferredGracePeriodMonths",
            "baseName": "deferredGracePeriodMonths",
            "type": "string"
        },
        {
            "name": "issuerPromotion",
            "baseName": "issuerPromotion",
            "type": "string"
        }
    ];
    return InstallmentParameters;
}());
exports.InstallmentParameters = InstallmentParameters;
