"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelError = void 0;
/**
* A single error
*/
var ModelError = /** @class */ (function () {
    function ModelError() {
    }
    ModelError.getAttributeTypeMap = function () {
        return ModelError.attributeTypeMap;
    };
    ModelError.discriminator = undefined;
    ModelError.attributeTypeMap = [
        {
            "name": "source",
            "baseName": "Source",
            "type": "string"
        },
        {
            "name": "reasonCode",
            "baseName": "ReasonCode",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string"
        },
        {
            "name": "recoverable",
            "baseName": "Recoverable",
            "type": "boolean"
        },
        {
            "name": "details",
            "baseName": "Details",
            "type": "string"
        }
    ];
    return ModelError;
}());
exports.ModelError = ModelError;
