"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueueDefinitionsList = void 0;
var QueueDefinitionsList = /** @class */ (function () {
    function QueueDefinitionsList() {
    }
    QueueDefinitionsList.getAttributeTypeMap = function () {
        return QueueDefinitionsList.attributeTypeMap;
    };
    QueueDefinitionsList.discriminator = undefined;
    QueueDefinitionsList.attributeTypeMap = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "definitions",
            "baseName": "definitions",
            "type": "Array<QueueDefinition>"
        }
    ];
    return QueueDefinitionsList;
}());
exports.QueueDefinitionsList = QueueDefinitionsList;
