"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueueField = void 0;
/**
* A field that can be fetched from this queue.
*/
var QueueField = /** @class */ (function () {
    function QueueField() {
    }
    QueueField.getAttributeTypeMap = function () {
        return QueueField.attributeTypeMap;
    };
    QueueField.discriminator = undefined;
    QueueField.attributeTypeMap = [
        {
            "name": "fieldName",
            "baseName": "fieldName",
            "type": "string"
        },
        {
            "name": "fieldDataType",
            "baseName": "fieldDataType",
            "type": "string"
        }
    ];
    return QueueField;
}());
exports.QueueField = QueueField;
