"use strict";
/**
 * Mastercom Extended API
 * The Mastercom Extended API consists of endpoints used by issuers and acquirers to manage Single Message System disputes.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RepresentmentReversalDetails = void 0;
var RepresentmentReversalDetails = /** @class */ (function () {
    function RepresentmentReversalDetails() {
    }
    RepresentmentReversalDetails.getAttributeTypeMap = function () {
        return RepresentmentReversalDetails.attributeTypeMap;
    };
    RepresentmentReversalDetails.discriminator = undefined;
    RepresentmentReversalDetails.attributeTypeMap = [
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "string"
        },
        {
            "name": "eventExpiryDateTime",
            "baseName": "eventExpiryDateTime",
            "type": "string"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "eventReferenceId",
            "baseName": "eventReferenceId",
            "type": "string"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string"
        },
        {
            "name": "creationDate",
            "baseName": "creationDate",
            "type": "string"
        },
        {
            "name": "clearingStatus",
            "baseName": "clearingStatus",
            "type": "string"
        },
        {
            "name": "rejectCode",
            "baseName": "rejectCode",
            "type": "string"
        },
        {
            "name": "rejectReason",
            "baseName": "rejectReason",
            "type": "string"
        },
        {
            "name": "eventLastModifiedBy",
            "baseName": "eventLastModifiedBy",
            "type": "string"
        },
        {
            "name": "lastUpdatedDateTime",
            "baseName": "lastUpdatedDateTime",
            "type": "string"
        },
        {
            "name": "singleMessage",
            "baseName": "singleMessage",
            "type": "RepresentmentReversalDetailsSingleMessage"
        }
    ];
    return RepresentmentReversalDetails;
}());
exports.RepresentmentReversalDetails = RepresentmentReversalDetails;
