"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RetrievalStatusRequestStructure = void 0;
var RetrievalStatusRequestStructure = /** @class */ (function () {
    function RetrievalStatusRequestStructure() {
    }
    RetrievalStatusRequestStructure.getAttributeTypeMap = function () {
        return RetrievalStatusRequestStructure.attributeTypeMap;
    };
    RetrievalStatusRequestStructure.discriminator = undefined;
    RetrievalStatusRequestStructure.attributeTypeMap = [
        {
            "name": "claimId",
            "baseName": "claimId",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string"
        }
    ];
    return RetrievalStatusRequestStructure;
}());
exports.RetrievalStatusRequestStructure = RetrievalStatusRequestStructure;
