"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RetrievalStatusRequest = void 0;
var RetrievalStatusRequest = /** @class */ (function () {
    function RetrievalStatusRequest() {
    }
    RetrievalStatusRequest.getAttributeTypeMap = function () {
        return RetrievalStatusRequest.attributeTypeMap;
    };
    RetrievalStatusRequest.discriminator = undefined;
    RetrievalStatusRequest.attributeTypeMap = [
        {
            "name": "retrievalList",
            "baseName": "retrievalList",
            "type": "Array<RetrievalStatusRequestStructure>"
        }
    ];
    return RetrievalStatusRequest;
}());
exports.RetrievalStatusRequest = RetrievalStatusRequest;
