"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RetrievalsImageStatusRequest = void 0;
var RetrievalsImageStatusRequest = /** @class */ (function () {
    function RetrievalsImageStatusRequest() {
    }
    RetrievalsImageStatusRequest.getAttributeTypeMap = function () {
        return RetrievalsImageStatusRequest.attributeTypeMap;
    };
    RetrievalsImageStatusRequest.discriminator = undefined;
    RetrievalsImageStatusRequest.attributeTypeMap = [
        {
            "name": "status",
            "baseName": "status",
            "type": "RetrievalsImageStatusRequest.StatusEnum"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        }
    ];
    return RetrievalsImageStatusRequest;
}());
exports.RetrievalsImageStatusRequest = RetrievalsImageStatusRequest;
(function (RetrievalsImageStatusRequest) {
    var StatusEnum;
    (function (StatusEnum) {
        StatusEnum[StatusEnum["Completed"] = 'COMPLETED'] = "Completed";
        StatusEnum[StatusEnum["Failed"] = 'FAILED'] = "Failed";
        StatusEnum[StatusEnum["Pending"] = 'PENDING'] = "Pending";
        StatusEnum[StatusEnum["Unavailable"] = 'UNAVAILABLE'] = "Unavailable";
        StatusEnum[StatusEnum["DocNotApplicable"] = 'DOC_NOT_APPLICABLE'] = "DocNotApplicable";
    })(StatusEnum = RetrievalsImageStatusRequest.StatusEnum || (RetrievalsImageStatusRequest.StatusEnum = {}));
})(RetrievalsImageStatusRequest || (exports.RetrievalsImageStatusRequest = RetrievalsImageStatusRequest = {}));
