/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionSingleMessageSummary } from './transactionSingleMessageSummary';

export class TransactionSingleMessageSummaryList {
    'transactionSummaryList'?: Array<TransactionSingleMessageSummary>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionSummaryList",
            "baseName": "transactionSummaryList",
            "type": "Array<TransactionSingleMessageSummary>"
        }    ];

    static getAttributeTypeMap() {
        return TransactionSingleMessageSummaryList.attributeTypeMap;
    }
}

