"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionSingleMessageSummary = void 0;
var TransactionSingleMessageSummary = /** @class */ (function () {
    function TransactionSingleMessageSummary() {
    }
    TransactionSingleMessageSummary.getAttributeTypeMap = function () {
        return TransactionSingleMessageSummary.attributeTypeMap;
    };
    TransactionSingleMessageSummary.discriminator = undefined;
    TransactionSingleMessageSummary.attributeTypeMap = [
        {
            "name": "authTransactionId",
            "baseName": "authTransactionId",
            "type": "string"
        },
        {
            "name": "clearingTransactionId",
            "baseName": "clearingTransactionId",
            "type": "string"
        },
        {
            "name": "singleMessageSummaryDetails",
            "baseName": "singleMessageSummaryDetails",
            "type": "SingleMessageSummaryDetails"
        }
    ];
    return TransactionSingleMessageSummary;
}());
exports.TransactionSingleMessageSummary = TransactionSingleMessageSummary;
