"use strict";
/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateClaimRequest = void 0;
var UpdateClaimRequest = /** @class */ (function () {
    function UpdateClaimRequest() {
    }
    UpdateClaimRequest.getAttributeTypeMap = function () {
        return UpdateClaimRequest.attributeTypeMap;
    };
    UpdateClaimRequest.discriminator = undefined;
    UpdateClaimRequest.attributeTypeMap = [
        {
            "name": "openClaimDueDate",
            "baseName": "openClaimDueDate",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "UpdateClaimRequest.ActionEnum"
        },
        {
            "name": "closeClaimReasonCode",
            "baseName": "closeClaimReasonCode",
            "type": "UpdateClaimRequest.CloseClaimReasonCodeEnum"
        }
    ];
    return UpdateClaimRequest;
}());
exports.UpdateClaimRequest = UpdateClaimRequest;
(function (UpdateClaimRequest) {
    var ActionEnum;
    (function (ActionEnum) {
        ActionEnum[ActionEnum["Reopen"] = 'REOPEN'] = "Reopen";
        ActionEnum[ActionEnum["Close"] = 'CLOSE'] = "Close";
    })(ActionEnum = UpdateClaimRequest.ActionEnum || (UpdateClaimRequest.ActionEnum = {}));
    var CloseClaimReasonCodeEnum;
    (function (CloseClaimReasonCodeEnum) {
        CloseClaimReasonCodeEnum[CloseClaimReasonCodeEnum["_10"] = '10'] = "_10";
        CloseClaimReasonCodeEnum[CloseClaimReasonCodeEnum["_20"] = '20'] = "_20";
        CloseClaimReasonCodeEnum[CloseClaimReasonCodeEnum["_30"] = '30'] = "_30";
        CloseClaimReasonCodeEnum[CloseClaimReasonCodeEnum["_40"] = '40'] = "_40";
    })(CloseClaimReasonCodeEnum = UpdateClaimRequest.CloseClaimReasonCodeEnum || (UpdateClaimRequest.CloseClaimReasonCodeEnum = {}));
})(UpdateClaimRequest || (exports.UpdateClaimRequest = UpdateClaimRequest = {}));
