/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CardholderDisputeChargebackDrfDocumentStructure model module.
 * @module model/CardholderDisputeChargebackDrfDocumentStructure
 * @version v6
 */
class CardholderDisputeChargebackDrfDocumentStructure {
    /**
     * Constructs a new <code>CardholderDisputeChargebackDrfDocumentStructure</code>.
     * @alias module:model/CardholderDisputeChargebackDrfDocumentStructure
     */
    constructor() { 
        
        CardholderDisputeChargebackDrfDocumentStructure.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardholderDisputeChargebackDrfDocumentStructure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardholderDisputeChargebackDrfDocumentStructure} obj Optional instance to populate.
     * @return {module:model/CardholderDisputeChargebackDrfDocumentStructure} The populated <code>CardholderDisputeChargebackDrfDocumentStructure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardholderDisputeChargebackDrfDocumentStructure();

            if (data.hasOwnProperty('transactionAmount')) {
                obj['transactionAmount'] = ApiClient.convertToType(data['transactionAmount'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('deliveryDateOfGoodsOrServices')) {
                obj['deliveryDateOfGoodsOrServices'] = ApiClient.convertToType(data['deliveryDateOfGoodsOrServices'], 'String');
            }
            if (data.hasOwnProperty('expectedDeliveryDateOfGoodOrServices')) {
                obj['expectedDeliveryDateOfGoodOrServices'] = ApiClient.convertToType(data['expectedDeliveryDateOfGoodOrServices'], 'String');
            }
            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'String');
            }
            if (data.hasOwnProperty('cancellationDate')) {
                obj['cancellationDate'] = ApiClient.convertToType(data['cancellationDate'], 'String');
            }
            if (data.hasOwnProperty('cardholderParticipation')) {
                obj['cardholderParticipation'] = ApiClient.convertToType(data['cardholderParticipation'], 'Boolean');
            }
            if (data.hasOwnProperty('disputeDetails')) {
                obj['disputeDetails'] = ApiClient.convertToType(data['disputeDetails'], 'String');
            }
            if (data.hasOwnProperty('chargebackRepresentative')) {
                obj['chargebackRepresentative'] = ApiClient.convertToType(data['chargebackRepresentative'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CardholderDisputeChargebackDrfDocumentStructure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CardholderDisputeChargebackDrfDocumentStructure</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionAmount'] && !(typeof data['transactionAmount'] === 'string' || data['transactionAmount'] instanceof String)) {
            throw new Error("Expected the field `transactionAmount` to be a primitive type in the JSON string but got " + data['transactionAmount']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['deliveryDateOfGoodsOrServices'] && !(typeof data['deliveryDateOfGoodsOrServices'] === 'string' || data['deliveryDateOfGoodsOrServices'] instanceof String)) {
            throw new Error("Expected the field `deliveryDateOfGoodsOrServices` to be a primitive type in the JSON string but got " + data['deliveryDateOfGoodsOrServices']);
        }
        // ensure the json data is a string
        if (data['expectedDeliveryDateOfGoodOrServices'] && !(typeof data['expectedDeliveryDateOfGoodOrServices'] === 'string' || data['expectedDeliveryDateOfGoodOrServices'] instanceof String)) {
            throw new Error("Expected the field `expectedDeliveryDateOfGoodOrServices` to be a primitive type in the JSON string but got " + data['expectedDeliveryDateOfGoodOrServices']);
        }
        // ensure the json data is a string
        if (data['returnDate'] && !(typeof data['returnDate'] === 'string' || data['returnDate'] instanceof String)) {
            throw new Error("Expected the field `returnDate` to be a primitive type in the JSON string but got " + data['returnDate']);
        }
        // ensure the json data is a string
        if (data['cancellationDate'] && !(typeof data['cancellationDate'] === 'string' || data['cancellationDate'] instanceof String)) {
            throw new Error("Expected the field `cancellationDate` to be a primitive type in the JSON string but got " + data['cancellationDate']);
        }
        // ensure the json data is a string
        if (data['disputeDetails'] && !(typeof data['disputeDetails'] === 'string' || data['disputeDetails'] instanceof String)) {
            throw new Error("Expected the field `disputeDetails` to be a primitive type in the JSON string but got " + data['disputeDetails']);
        }
        // ensure the json data is a string
        if (data['chargebackRepresentative'] && !(typeof data['chargebackRepresentative'] === 'string' || data['chargebackRepresentative'] instanceof String)) {
            throw new Error("Expected the field `chargebackRepresentative` to be a primitive type in the JSON string but got " + data['chargebackRepresentative']);
        }

        return true;
    }


}



/**
 * The transaction amount.   Length: 0-12   Valid Values/Format: Numeric
 * @member {String} transactionAmount
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['transactionAmount'] = undefined;

/**
 * Type of Carholder Dispute.   Length: 11-22   Valid Values/Format: PRODUCT_DISPUTE,NOT_PROVIDED,DIGITAL_GOODS,CREDIT_NOT_PROCESSED,COUNTERFEIT,RECURRING_CANCELLED,RECURRING_DISCLOSURE,ADDENDUM_DISPUTE,HOTEL_NO_SHOW,PURCHASE_INCOMPLETE,CANCELLATION_AGREEMENT,POSTED_CREDIT,FAILED_TRAVEL
 * @member {module:model/CardholderDisputeChargebackDrfDocumentStructure.TypeEnum} type
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['type'] = undefined;

/**
 * CONDITIONAL: In case of PRODUCT_DISPUTE, delivery date of the goods or services.   Length: 11   Valid Values/Format: Date (dd-MMM-yyyy)
 * @member {String} deliveryDateOfGoodsOrServices
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['deliveryDateOfGoodsOrServices'] = undefined;

/**
 * CONDITIONAL: In case of NOT_PROVIDED, expected delivery date of the goods or services.   Length: 11   Valid Values/Format: Date (dd-MMM-yyyy)
 * @member {String} expectedDeliveryDateOfGoodOrServices
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['expectedDeliveryDateOfGoodOrServices'] = undefined;

/**
 * CONDITIONAL: In case of DIGITAL_GOODS, return or cancellation of the goods or services.   Length: 11   Valid Values/Format: Date (dd-MMM-yyyy)
 * @member {String} returnDate
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['returnDate'] = undefined;

/**
 * CONDITIONAL: In case of RECURRING_CANCELLED, cancellation of the goods or services.   Length: 11   Valid Values/Format: Date (dd-MMM-yyyy)
 * @member {String} cancellationDate
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['cancellationDate'] = undefined;

/**
 * Did the cardholder participate in the transaction?   Length: 4-5   Valid Values/Format: true / false
 * @member {Boolean} cardholderParticipation
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['cardholderParticipation'] = undefined;

/**
 * Describe the cardholderâ€™s compliant in sufficient detail to meet the requirements for the chargeback as described in the Chargeback Guide and to enable all parties to understand the dispute.   Length: 0-3000   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&*()_+{}|:\"<>?,./;'[]-=)
 * @member {String} disputeDetails
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['disputeDetails'] = undefined;

/**
 * Customer Service/Chargeback Representative.   Length: 0-25   Valid Values/Format: Alphanumeric / Special Char (~!@#$%^&*()_+{}|:\"<>?,./;'[]-=)
 * @member {String} chargebackRepresentative
 */
CardholderDisputeChargebackDrfDocumentStructure.prototype['chargebackRepresentative'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CardholderDisputeChargebackDrfDocumentStructure['TypeEnum'] = {

    /**
     * value: "PRODUCT_DISPUTE"
     * @const
     */
    "PRODUCT_DISPUTE": "PRODUCT_DISPUTE",

    /**
     * value: "NOT_PROVIDED"
     * @const
     */
    "NOT_PROVIDED": "NOT_PROVIDED",

    /**
     * value: "DIGITAL_GOODS"
     * @const
     */
    "DIGITAL_GOODS": "DIGITAL_GOODS",

    /**
     * value: "CREDIT_NOT_PROCESSED"
     * @const
     */
    "CREDIT_NOT_PROCESSED": "CREDIT_NOT_PROCESSED",

    /**
     * value: "COUNTERFEIT"
     * @const
     */
    "COUNTERFEIT": "COUNTERFEIT",

    /**
     * value: "RECURRING_CANCELLED"
     * @const
     */
    "RECURRING_CANCELLED": "RECURRING_CANCELLED",

    /**
     * value: "RECURRING_DISCLOSURE"
     * @const
     */
    "RECURRING_DISCLOSURE": "RECURRING_DISCLOSURE",

    /**
     * value: "ADDENDUM_DISPUTE"
     * @const
     */
    "ADDENDUM_DISPUTE": "ADDENDUM_DISPUTE",

    /**
     * value: "HOTEL_NO_SHOW"
     * @const
     */
    "HOTEL_NO_SHOW": "HOTEL_NO_SHOW",

    /**
     * value: "PURCHASE_INCOMPLETE"
     * @const
     */
    "PURCHASE_INCOMPLETE": "PURCHASE_INCOMPLETE",

    /**
     * value: "CANCELLATION_AGREEMENT"
     * @const
     */
    "CANCELLATION_AGREEMENT": "CANCELLATION_AGREEMENT",

    /**
     * value: "POSTED_CREDIT"
     * @const
     */
    "POSTED_CREDIT": "POSTED_CREDIT",

    /**
     * value: "FAILED_TRAVEL"
     * @const
     */
    "FAILED_TRAVEL": "FAILED_TRAVEL"
};



export default CardholderDisputeChargebackDrfDocumentStructure;

