/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CaseFilingDetails from './CaseFilingDetails';
import CaseFilingRespHistory from './CaseFilingRespHistory';

/**
 * The CaseFilingLifeCycle model module.
 * @module model/CaseFilingLifeCycle
 * @version v6
 */
class CaseFilingLifeCycle {
    /**
     * Constructs a new <code>CaseFilingLifeCycle</code>.
     * @alias module:model/CaseFilingLifeCycle
     */
    constructor() { 
        
        CaseFilingLifeCycle.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CaseFilingLifeCycle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CaseFilingLifeCycle} obj Optional instance to populate.
     * @return {module:model/CaseFilingLifeCycle} The populated <code>CaseFilingLifeCycle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CaseFilingLifeCycle();

            if (data.hasOwnProperty('caseFilingStatus')) {
                obj['caseFilingStatus'] = ApiClient.convertToType(data['caseFilingStatus'], 'String');
            }
            if (data.hasOwnProperty('caseFilingDetails')) {
                obj['caseFilingDetails'] = CaseFilingDetails.constructFromObject(data['caseFilingDetails']);
            }
            if (data.hasOwnProperty('caseFilingRespHistory')) {
                obj['caseFilingRespHistory'] = ApiClient.convertToType(data['caseFilingRespHistory'], [CaseFilingRespHistory]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CaseFilingLifeCycle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CaseFilingLifeCycle</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['caseFilingStatus'] && !(typeof data['caseFilingStatus'] === 'string' || data['caseFilingStatus'] instanceof String)) {
            throw new Error("Expected the field `caseFilingStatus` to be a primitive type in the JSON string but got " + data['caseFilingStatus']);
        }
        // validate the optional field `caseFilingDetails`
        if (data['caseFilingDetails']) { // data not null
          CaseFilingDetails.validateJSON(data['caseFilingDetails']);
        }
        if (data['caseFilingRespHistory']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['caseFilingRespHistory'])) {
                throw new Error("Expected the field `caseFilingRespHistory` to be an array in the JSON data but got " + data['caseFilingRespHistory']);
            }
            // validate the optional field `caseFilingRespHistory` (array)
            for (const item of data['caseFilingRespHistory']) {
                CaseFilingRespHistory.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Case Filing Status
 * @member {String} caseFilingStatus
 */
CaseFilingLifeCycle.prototype['caseFilingStatus'] = undefined;

/**
 * @member {module:model/CaseFilingDetails} caseFilingDetails
 */
CaseFilingLifeCycle.prototype['caseFilingDetails'] = undefined;

/**
 * @member {Array.<module:model/CaseFilingRespHistory>} caseFilingRespHistory
 */
CaseFilingLifeCycle.prototype['caseFilingRespHistory'] = undefined;






export default CaseFilingLifeCycle;

