/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CaseFilingImageStatusResponseStructure from './CaseFilingImageStatusResponseStructure';

/**
 * The CaseFilingImageStatusResponse model module.
 * @module model/CaseFilingImageStatusResponse
 * @version v6
 */
class CaseFilingImageStatusResponse {
    /**
     * Constructs a new <code>CaseFilingImageStatusResponse</code>.
     * @alias module:model/CaseFilingImageStatusResponse
     */
    constructor() { 
        
        CaseFilingImageStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CaseFilingImageStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CaseFilingImageStatusResponse} obj Optional instance to populate.
     * @return {module:model/CaseFilingImageStatusResponse} The populated <code>CaseFilingImageStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CaseFilingImageStatusResponse();

            if (data.hasOwnProperty('caseFilingImageStatusList')) {
                obj['caseFilingImageStatusList'] = ApiClient.convertToType(data['caseFilingImageStatusList'], [CaseFilingImageStatusResponseStructure]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CaseFilingImageStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CaseFilingImageStatusResponse</code>.
     */
    static validateJSON(data) {
        if (data['caseFilingImageStatusList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['caseFilingImageStatusList'])) {
                throw new Error("Expected the field `caseFilingImageStatusList` to be an array in the JSON data but got " + data['caseFilingImageStatusList']);
            }
            // validate the optional field `caseFilingImageStatusList` (array)
            for (const item of data['caseFilingImageStatusList']) {
                CaseFilingImageStatusResponseStructure.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * A list of case filing image statuses
 * @member {Array.<module:model/CaseFilingImageStatusResponseStructure>} caseFilingImageStatusList
 */
CaseFilingImageStatusResponse.prototype['caseFilingImageStatusList'] = undefined;






export default CaseFilingImageStatusResponse;

