/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChargebackImageStatusResponseStructure from './ChargebackImageStatusResponseStructure';

/**
 * The ChargebackImageStatusResponse model module.
 * @module model/ChargebackImageStatusResponse
 * @version v6
 */
class ChargebackImageStatusResponse {
    /**
     * Constructs a new <code>ChargebackImageStatusResponse</code>.
     * @alias module:model/ChargebackImageStatusResponse
     */
    constructor() { 
        
        ChargebackImageStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChargebackImageStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChargebackImageStatusResponse} obj Optional instance to populate.
     * @return {module:model/ChargebackImageStatusResponse} The populated <code>ChargebackImageStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChargebackImageStatusResponse();

            if (data.hasOwnProperty('chargebackImageStatusList')) {
                obj['chargebackImageStatusList'] = ApiClient.convertToType(data['chargebackImageStatusList'], [ChargebackImageStatusResponseStructure]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChargebackImageStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChargebackImageStatusResponse</code>.
     */
    static validateJSON(data) {
        if (data['chargebackImageStatusList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['chargebackImageStatusList'])) {
                throw new Error("Expected the field `chargebackImageStatusList` to be an array in the JSON data but got " + data['chargebackImageStatusList']);
            }
            // validate the optional field `chargebackImageStatusList` (array)
            for (const item of data['chargebackImageStatusList']) {
                ChargebackImageStatusResponseStructure.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * A list of chargeback image statuses
 * @member {Array.<module:model/ChargebackImageStatusResponseStructure>} chargebackImageStatusList
 */
ChargebackImageStatusResponse.prototype['chargebackImageStatusList'] = undefined;






export default ChargebackImageStatusResponse;

