/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChargebackDetails model module.
 * @module model/ChargebackDetails
 * @version v6
 */
class ChargebackDetails {
    /**
     * Constructs a new <code>ChargebackDetails</code>.
     * @alias module:model/ChargebackDetails
     */
    constructor() { 
        
        ChargebackDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChargebackDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChargebackDetails} obj Optional instance to populate.
     * @return {module:model/ChargebackDetails} The populated <code>ChargebackDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChargebackDetails();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
            }
            if (data.hasOwnProperty('documentIndicator')) {
                obj['documentIndicator'] = ApiClient.convertToType(data['documentIndicator'], 'String');
            }
            if (data.hasOwnProperty('messageText')) {
                obj['messageText'] = ApiClient.convertToType(data['messageText'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('reasonCode')) {
                obj['reasonCode'] = ApiClient.convertToType(data['reasonCode'], 'String');
            }
            if (data.hasOwnProperty('isPartialChargeback')) {
                obj['isPartialChargeback'] = ApiClient.convertToType(data['isPartialChargeback'], 'Boolean');
            }
            if (data.hasOwnProperty('chargebackType')) {
                obj['chargebackType'] = ApiClient.convertToType(data['chargebackType'], 'String');
            }
            if (data.hasOwnProperty('chargebackId')) {
                obj['chargebackId'] = ApiClient.convertToType(data['chargebackId'], 'String');
            }
            if (data.hasOwnProperty('claimId')) {
                obj['claimId'] = ApiClient.convertToType(data['claimId'], 'String');
            }
            if (data.hasOwnProperty('reversed')) {
                obj['reversed'] = ApiClient.convertToType(data['reversed'], 'Boolean');
            }
            if (data.hasOwnProperty('reversal')) {
                obj['reversal'] = ApiClient.convertToType(data['reversal'], 'Boolean');
            }
            if (data.hasOwnProperty('chargebackRefNum')) {
                obj['chargebackRefNum'] = ApiClient.convertToType(data['chargebackRefNum'], 'String');
            }
            if (data.hasOwnProperty('documentStatus')) {
                obj['documentStatus'] = ApiClient.convertToType(data['documentStatus'], 'String');
            }
            if (data.hasOwnProperty('reconciliationAmount')) {
                obj['reconciliationAmount'] = ApiClient.convertToType(data['reconciliationAmount'], 'String');
            }
            if (data.hasOwnProperty('reconciliationCurrency')) {
                obj['reconciliationCurrency'] = ApiClient.convertToType(data['reconciliationCurrency'], 'String');
            }
            if (data.hasOwnProperty('rejectReason')) {
                obj['rejectReason'] = ApiClient.convertToType(data['rejectReason'], 'String');
            }
            if (data.hasOwnProperty('editExclusionCode')) {
                obj['editExclusionCode'] = ApiClient.convertToType(data['editExclusionCode'], 'String');
            }
            if (data.hasOwnProperty('refundNotReceivedIndicator')) {
                obj['refundNotReceivedIndicator'] = ApiClient.convertToType(data['refundNotReceivedIndicator'], 'String');
            }
            if (data.hasOwnProperty('creditVoucherStatus')) {
                obj['creditVoucherStatus'] = ApiClient.convertToType(data['creditVoucherStatus'], 'String');
            }
            if (data.hasOwnProperty('currencyConversionAssessmentCCAIncluded')) {
                obj['currencyConversionAssessmentCCAIncluded'] = ApiClient.convertToType(data['currencyConversionAssessmentCCAIncluded'], 'String');
            }
            if (data.hasOwnProperty('currencyConversionAssessmentCCAAmount')) {
                obj['currencyConversionAssessmentCCAAmount'] = ApiClient.convertToType(data['currencyConversionAssessmentCCAAmount'], 'String');
            }
            if (data.hasOwnProperty('japanCommonMerchantCode')) {
                obj['japanCommonMerchantCode'] = ApiClient.convertToType(data['japanCommonMerchantCode'], 'String');
            }
            if (data.hasOwnProperty('installmentData')) {
                obj['installmentData'] = ApiClient.convertToType(data['installmentData'], 'String');
            }
            if (data.hasOwnProperty('flexCode')) {
                obj['flexCode'] = ApiClient.convertToType(data['flexCode'], 'String');
            }
            if (data.hasOwnProperty('acknowledgeFirstPartyTrustEvidence')) {
                obj['acknowledgeFirstPartyTrustEvidence'] = ApiClient.convertToType(data['acknowledgeFirstPartyTrustEvidence'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChargebackDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChargebackDetails</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['createDate'] && !(typeof data['createDate'] === 'string' || data['createDate'] instanceof String)) {
            throw new Error("Expected the field `createDate` to be a primitive type in the JSON string but got " + data['createDate']);
        }
        // ensure the json data is a string
        if (data['documentIndicator'] && !(typeof data['documentIndicator'] === 'string' || data['documentIndicator'] instanceof String)) {
            throw new Error("Expected the field `documentIndicator` to be a primitive type in the JSON string but got " + data['documentIndicator']);
        }
        // ensure the json data is a string
        if (data['messageText'] && !(typeof data['messageText'] === 'string' || data['messageText'] instanceof String)) {
            throw new Error("Expected the field `messageText` to be a primitive type in the JSON string but got " + data['messageText']);
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['reasonCode'] && !(typeof data['reasonCode'] === 'string' || data['reasonCode'] instanceof String)) {
            throw new Error("Expected the field `reasonCode` to be a primitive type in the JSON string but got " + data['reasonCode']);
        }
        // ensure the json data is a string
        if (data['chargebackType'] && !(typeof data['chargebackType'] === 'string' || data['chargebackType'] instanceof String)) {
            throw new Error("Expected the field `chargebackType` to be a primitive type in the JSON string but got " + data['chargebackType']);
        }
        // ensure the json data is a string
        if (data['chargebackId'] && !(typeof data['chargebackId'] === 'string' || data['chargebackId'] instanceof String)) {
            throw new Error("Expected the field `chargebackId` to be a primitive type in the JSON string but got " + data['chargebackId']);
        }
        // ensure the json data is a string
        if (data['claimId'] && !(typeof data['claimId'] === 'string' || data['claimId'] instanceof String)) {
            throw new Error("Expected the field `claimId` to be a primitive type in the JSON string but got " + data['claimId']);
        }
        // ensure the json data is a string
        if (data['chargebackRefNum'] && !(typeof data['chargebackRefNum'] === 'string' || data['chargebackRefNum'] instanceof String)) {
            throw new Error("Expected the field `chargebackRefNum` to be a primitive type in the JSON string but got " + data['chargebackRefNum']);
        }
        // ensure the json data is a string
        if (data['documentStatus'] && !(typeof data['documentStatus'] === 'string' || data['documentStatus'] instanceof String)) {
            throw new Error("Expected the field `documentStatus` to be a primitive type in the JSON string but got " + data['documentStatus']);
        }
        // ensure the json data is a string
        if (data['reconciliationAmount'] && !(typeof data['reconciliationAmount'] === 'string' || data['reconciliationAmount'] instanceof String)) {
            throw new Error("Expected the field `reconciliationAmount` to be a primitive type in the JSON string but got " + data['reconciliationAmount']);
        }
        // ensure the json data is a string
        if (data['reconciliationCurrency'] && !(typeof data['reconciliationCurrency'] === 'string' || data['reconciliationCurrency'] instanceof String)) {
            throw new Error("Expected the field `reconciliationCurrency` to be a primitive type in the JSON string but got " + data['reconciliationCurrency']);
        }
        // ensure the json data is a string
        if (data['rejectReason'] && !(typeof data['rejectReason'] === 'string' || data['rejectReason'] instanceof String)) {
            throw new Error("Expected the field `rejectReason` to be a primitive type in the JSON string but got " + data['rejectReason']);
        }
        // ensure the json data is a string
        if (data['editExclusionCode'] && !(typeof data['editExclusionCode'] === 'string' || data['editExclusionCode'] instanceof String)) {
            throw new Error("Expected the field `editExclusionCode` to be a primitive type in the JSON string but got " + data['editExclusionCode']);
        }
        // ensure the json data is a string
        if (data['refundNotReceivedIndicator'] && !(typeof data['refundNotReceivedIndicator'] === 'string' || data['refundNotReceivedIndicator'] instanceof String)) {
            throw new Error("Expected the field `refundNotReceivedIndicator` to be a primitive type in the JSON string but got " + data['refundNotReceivedIndicator']);
        }
        // ensure the json data is a string
        if (data['creditVoucherStatus'] && !(typeof data['creditVoucherStatus'] === 'string' || data['creditVoucherStatus'] instanceof String)) {
            throw new Error("Expected the field `creditVoucherStatus` to be a primitive type in the JSON string but got " + data['creditVoucherStatus']);
        }
        // ensure the json data is a string
        if (data['currencyConversionAssessmentCCAIncluded'] && !(typeof data['currencyConversionAssessmentCCAIncluded'] === 'string' || data['currencyConversionAssessmentCCAIncluded'] instanceof String)) {
            throw new Error("Expected the field `currencyConversionAssessmentCCAIncluded` to be a primitive type in the JSON string but got " + data['currencyConversionAssessmentCCAIncluded']);
        }
        // ensure the json data is a string
        if (data['currencyConversionAssessmentCCAAmount'] && !(typeof data['currencyConversionAssessmentCCAAmount'] === 'string' || data['currencyConversionAssessmentCCAAmount'] instanceof String)) {
            throw new Error("Expected the field `currencyConversionAssessmentCCAAmount` to be a primitive type in the JSON string but got " + data['currencyConversionAssessmentCCAAmount']);
        }
        // ensure the json data is a string
        if (data['japanCommonMerchantCode'] && !(typeof data['japanCommonMerchantCode'] === 'string' || data['japanCommonMerchantCode'] instanceof String)) {
            throw new Error("Expected the field `japanCommonMerchantCode` to be a primitive type in the JSON string but got " + data['japanCommonMerchantCode']);
        }
        // ensure the json data is a string
        if (data['installmentData'] && !(typeof data['installmentData'] === 'string' || data['installmentData'] instanceof String)) {
            throw new Error("Expected the field `installmentData` to be a primitive type in the JSON string but got " + data['installmentData']);
        }
        // ensure the json data is a string
        if (data['flexCode'] && !(typeof data['flexCode'] === 'string' || data['flexCode'] instanceof String)) {
            throw new Error("Expected the field `flexCode` to be a primitive type in the JSON string but got " + data['flexCode']);
        }
        // ensure the json data is a string
        if (data['acknowledgeFirstPartyTrustEvidence'] && !(typeof data['acknowledgeFirstPartyTrustEvidence'] === 'string' || data['acknowledgeFirstPartyTrustEvidence'] instanceof String)) {
            throw new Error("Expected the field `acknowledgeFirstPartyTrustEvidence` to be a primitive type in the JSON string but got " + data['acknowledgeFirstPartyTrustEvidence']);
        }

        return true;
    }


}



/**
 * The chargeback currency.  The data should be standard currency alpha code
 * @member {String} currency
 */
ChargebackDetails.prototype['currency'] = undefined;

/**
 * This is the date of the chargeback creation
 * @member {String} createDate
 */
ChargebackDetails.prototype['createDate'] = undefined;

/**
 * Document Indicator
 * @member {String} documentIndicator
 */
ChargebackDetails.prototype['documentIndicator'] = undefined;

/**
 * Member message text to be used for the chargeback
 * @member {String} messageText
 */
ChargebackDetails.prototype['messageText'] = undefined;

/**
 * Chargeback Amount
 * @member {String} amount
 */
ChargebackDetails.prototype['amount'] = undefined;

/**
 * Chargeback Reason Code
 * @member {String} reasonCode
 */
ChargebackDetails.prototype['reasonCode'] = undefined;

/**
 * Indicates a partial chargeback
 * @member {Boolean} isPartialChargeback
 */
ChargebackDetails.prototype['isPartialChargeback'] = undefined;

/**
 * Provide the chargeback type.  The following values are valid - CHARGEBACK, SECOND_PRESENTMENT
 * @member {module:model/ChargebackDetails.ChargebackTypeEnum} chargebackType
 */
ChargebackDetails.prototype['chargebackType'] = undefined;

/**
 * Identifier assigned to the Chargeback
 * @member {String} chargebackId
 */
ChargebackDetails.prototype['chargebackId'] = undefined;

/**
 * Claim identifier
 * @member {String} claimId
 */
ChargebackDetails.prototype['claimId'] = undefined;

/**
 * Indicates this chargeback has been reversed
 * @member {Boolean} reversed
 */
ChargebackDetails.prototype['reversed'] = undefined;

/**
 * Indicates this chargeback is a reversal chargeback
 * @member {Boolean} reversal
 */
ChargebackDetails.prototype['reversal'] = undefined;

/**
 * Contains card issuer reference data for a specific cardholder transaction. This number must be unique within BIN. It is used to track the chargeback throughout its life cycle
 * @member {String} chargebackRefNum
 */
ChargebackDetails.prototype['chargebackRefNum'] = undefined;

/**
 * The document status on chargebacks is helpful for customers to identify the chargebacks that need documents to be uploaded within the stipulated 8 days limit for uploading documentation after chargeback creation.
 * @member {String} documentStatus
 */
ChargebackDetails.prototype['documentStatus'] = undefined;

/**
 * Reconciliation amount of the chargeback type. Amount will only be retrieved by the receiver side of the dispute cycle.
 * @member {String} reconciliationAmount
 */
ChargebackDetails.prototype['reconciliationAmount'] = undefined;

/**
 * Reconciliation currency of the chargeback type. Currency will only be retrieved by the receiver side of the dispute cycle.
 * @member {String} reconciliationCurrency
 */
ChargebackDetails.prototype['reconciliationCurrency'] = undefined;

/**
 * Chargeback reject reason.  Bridged chargeback reject reason - Possible values:   Code1=2802(00):D0025/000;DE072=D0025\\\\\\\\0000\\\\\\\\\\\\\\\\ - Ineligible chargeback reject reason codes 'FNS COUNTER EXCEEDED'   Code1=2801(00):D0025/000;DE072=D0025\\\\\\\\0000\\\\\\\\\\\\\\\\ - Ineligible chargeback reject reason codes 'FNS DATE EXCEEDED'   Code1=2570(00):D0025/000;DE072=D0025\\\\\\\\0000\\\\\\\\\\\\\\\\ - Chargeback not allowed beyond 120 days of transaction date   Code1=5050(00):D0025/000;DE072=D0025\\\\\\\\0000\\\\\\\\\\\\\\\\ - New amount and Org amount can't be equal   Code1=5051(00):D0025/000;DE072=D0025\\\\\\\\0000\\\\\\\\\\\\\\\\ - Other errors               
 * @member {String} rejectReason
 */
ChargebackDetails.prototype['rejectReason'] = undefined;

/**
 * Edit exclusion code to bypass clearing system edits. Valid Values - Y ,B0,B1,B2,B3,B4,B5,B6,B7,B8,B9,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ,SPACES.
 * @member {String} editExclusionCode
 */
ChargebackDetails.prototype['editExclusionCode'] = undefined;

/**
 * Cardholder/Issuer did not receive refund when a first chargeback was rejected by Collaboration with reason code 5000 indicating refund provided. 20 days after rejection of CB through collaboration. This field is only applicable if chargebackType is CHARGEBACK. Valid values are: true, false.
 * @member {String} refundNotReceivedIndicator
 */
ChargebackDetails.prototype['refundNotReceivedIndicator'] = undefined;

/**
 * The actual status of the credit voucher
 * @member {String} creditVoucherStatus
 */
ChargebackDetails.prototype['creditVoucherStatus'] = undefined;

/**
 * Currency Conversion Assessment amount applied for full first chargeback, to indicate, if Currency Conversion Assessment was included or not for qualified transactions.
 * @member {String} currencyConversionAssessmentCCAIncluded
 */
ChargebackDetails.prototype['currencyConversionAssessmentCCAIncluded'] = undefined;

/**
 * Currency Conversion Assessment amount Fee associated with fullÂ first chargeback.
 * @member {String} currencyConversionAssessmentCCAAmount
 */
ChargebackDetails.prototype['currencyConversionAssessmentCCAAmount'] = undefined;

/**
 * Identifies the merchant's category in Japan referred to as the Common Merchant Category Code (CMC). Mastercard uses this value to identify a link to a corresponding Mastercard Assigned ID.
 * @member {String} japanCommonMerchantCode
 */
ChargebackDetails.prototype['japanCommonMerchantCode'] = undefined;

/**
 * Provides information about the installment payment option selected by the cardholder at the point of interaction.
 * @member {String} installmentData
 */
ChargebackDetails.prototype['installmentData'] = undefined;

/**
 * Specific to Brazil Flex Card transactions to communicate the product code used for clearing.
 * @member {String} flexCode
 */
ChargebackDetails.prototype['flexCode'] = undefined;

/**
 * Issuer has acknowledged First-Party Trust evidence and proceeded with the chargeback.
 * @member {String} acknowledgeFirstPartyTrustEvidence
 */
ChargebackDetails.prototype['acknowledgeFirstPartyTrustEvidence'] = undefined;





/**
 * Allowed values for the <code>chargebackType</code> property.
 * @enum {String}
 * @readonly
 */
ChargebackDetails['ChargebackTypeEnum'] = {

    /**
     * value: "CHARGEBACK"
     * @const
     */
    "CHARGEBACK": "CHARGEBACK",

    /**
     * value: "SECOND_PRESENTMENT"
     * @const
     */
    "SECOND_PRESENTMENT": "SECOND_PRESENTMENT"
};



export default ChargebackDetails;

