/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChargebackMarkProcessedResponseStructure from './ChargebackMarkProcessedResponseStructure';

/**
 * The ChargebackMarkProcessedResponse model module.
 * @module model/ChargebackMarkProcessedResponse
 * @version v6
 */
class ChargebackMarkProcessedResponse {
    /**
     * Constructs a new <code>ChargebackMarkProcessedResponse</code>.
     * @alias module:model/ChargebackMarkProcessedResponse
     */
    constructor() { 
        
        ChargebackMarkProcessedResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChargebackMarkProcessedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChargebackMarkProcessedResponse} obj Optional instance to populate.
     * @return {module:model/ChargebackMarkProcessedResponse} The populated <code>ChargebackMarkProcessedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChargebackMarkProcessedResponse();

            if (data.hasOwnProperty('chargebackResponseList')) {
                obj['chargebackResponseList'] = ApiClient.convertToType(data['chargebackResponseList'], [ChargebackMarkProcessedResponseStructure]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChargebackMarkProcessedResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChargebackMarkProcessedResponse</code>.
     */
    static validateJSON(data) {
        if (data['chargebackResponseList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['chargebackResponseList'])) {
                throw new Error("Expected the field `chargebackResponseList` to be an array in the JSON data but got " + data['chargebackResponseList']);
            }
            // validate the optional field `chargebackResponseList` (array)
            for (const item of data['chargebackResponseList']) {
                ChargebackMarkProcessedResponseStructure.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * A list of Chargeback statuses
 * @member {Array.<module:model/ChargebackMarkProcessedResponseStructure>} chargebackResponseList
 */
ChargebackMarkProcessedResponse.prototype['chargebackResponseList'] = undefined;






export default ChargebackMarkProcessedResponse;

