/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RetrievalStatusResponseStructure from './RetrievalStatusResponseStructure';

/**
 * The RetrievalStatusResponse model module.
 * @module model/RetrievalStatusResponse
 * @version v6
 */
class RetrievalStatusResponse {
    /**
     * Constructs a new <code>RetrievalStatusResponse</code>.
     * @alias module:model/RetrievalStatusResponse
     */
    constructor() { 
        
        RetrievalStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RetrievalStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RetrievalStatusResponse} obj Optional instance to populate.
     * @return {module:model/RetrievalStatusResponse} The populated <code>RetrievalStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RetrievalStatusResponse();

            if (data.hasOwnProperty('retrievalResponseList')) {
                obj['retrievalResponseList'] = ApiClient.convertToType(data['retrievalResponseList'], [RetrievalStatusResponseStructure]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RetrievalStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RetrievalStatusResponse</code>.
     */
    static validateJSON(data) {
        if (data['retrievalResponseList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['retrievalResponseList'])) {
                throw new Error("Expected the field `retrievalResponseList` to be an array in the JSON data but got " + data['retrievalResponseList']);
            }
            // validate the optional field `retrievalResponseList` (array)
            for (const item of data['retrievalResponseList']) {
                RetrievalStatusResponseStructure.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * A list of retrieval image statuses
 * @member {Array.<module:model/RetrievalStatusResponseStructure>} retrievalResponseList
 */
RetrievalStatusResponse.prototype['retrievalResponseList'] = undefined;






export default RetrievalStatusResponse;

