/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SingleMessageDetail from './SingleMessageDetail';

/**
 * The TransactionSingleMessageDetail model module.
 * @module model/TransactionSingleMessageDetail
 * @version v6
 */
class TransactionSingleMessageDetail {
    /**
     * Constructs a new <code>TransactionSingleMessageDetail</code>.
     * @alias module:model/TransactionSingleMessageDetail
     */
    constructor() { 
        
        TransactionSingleMessageDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionSingleMessageDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionSingleMessageDetail} obj Optional instance to populate.
     * @return {module:model/TransactionSingleMessageDetail} The populated <code>TransactionSingleMessageDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionSingleMessageDetail();

            if (data.hasOwnProperty('authTransaction')) {
                obj['authTransaction'] = SingleMessageDetail.constructFromObject(data['authTransaction']);
            }
            if (data.hasOwnProperty('clearingTransaction')) {
                obj['clearingTransaction'] = SingleMessageDetail.constructFromObject(data['clearingTransaction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionSingleMessageDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionSingleMessageDetail</code>.
     */
    static validateJSON(data) {
        // validate the optional field `authTransaction`
        if (data['authTransaction']) { // data not null
          SingleMessageDetail.validateJSON(data['authTransaction']);
        }
        // validate the optional field `clearingTransaction`
        if (data['clearingTransaction']) { // data not null
          SingleMessageDetail.validateJSON(data['clearingTransaction']);
        }

        return true;
    }


}



/**
 * @member {module:model/SingleMessageDetail} authTransaction
 */
TransactionSingleMessageDetail.prototype['authTransaction'] = undefined;

/**
 * @member {module:model/SingleMessageDetail} clearingTransaction
 */
TransactionSingleMessageDetail.prototype['clearingTransaction'] = undefined;






export default TransactionSingleMessageDetail;

