/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.AcquirerFulfillmentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AcquirerFulfillmentRequest', function() {
    it('should create an instance of AcquirerFulfillmentRequest', function() {
      // uncomment below and update the code to test AcquirerFulfillmentRequest
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be.a(MasterCom.AcquirerFulfillmentRequest);
    });

    it('should have the property acquirerResponseCd (base name: "acquirerResponseCd")', function() {
      // uncomment below and update the code to test the property acquirerResponseCd
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

    it('should have the property refundReversalType (base name: "refundReversalType")', function() {
      // uncomment below and update the code to test the property refundReversalType
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

    it('should have the property refundReversalDate (base name: "refundReversalDate")', function() {
      // uncomment below and update the code to test the property refundReversalDate
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

    it('should have the property refundReversalAmount (base name: "refundReversalAmount")', function() {
      // uncomment below and update the code to test the property refundReversalAmount
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

    it('should have the property refundReversalCurrency (base name: "refundReversalCurrency")', function() {
      // uncomment below and update the code to test the property refundReversalCurrency
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

    it('should have the property refundReversalReferenceId (base name: "refundReversalReferenceId")', function() {
      // uncomment below and update the code to test the property refundReversalReferenceId
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

    it('should have the property memo (base name: "memo")', function() {
      // uncomment below and update the code to test the property memo
      //var instance = new MasterCom.AcquirerFulfillmentRequest();
      //expect(instance).to.be();
    });

  });

}));
