/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.AuthorizationDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthorizationDetail', function() {
    it('should create an instance of AuthorizationDetail', function() {
      // uncomment below and update the code to test AuthorizationDetail
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be.a(MasterCom.AuthorizationDetail);
    });

    it('should have the property accountNumber (base name: "accountNumber")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property accountNumberIndicator (base name: "accountNumberIndicator")', function() {
      // uncomment below and update the code to test the property accountNumberIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquirer (base name: "acquirer")', function() {
      // uncomment below and update the code to test the property acquirer
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquiringInstitutionCountryCode (base name: "acquiringInstitutionCountryCode")', function() {
      // uncomment below and update the code to test the property acquiringInstitutionCountryCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquiringInstitutionId (base name: "acquiringInstitutionId")', function() {
      // uncomment below and update the code to test the property acquiringInstitutionId
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property addressVerificationServiceResponse (base name: "addressVerificationServiceResponse")', function() {
      // uncomment below and update the code to test the property addressVerificationServiceResponse
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property adviceReasonCode (base name: "adviceReasonCode")', function() {
      // uncomment below and update the code to test the property adviceReasonCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property atcDiscrepancyIndicator (base name: "atcDiscrepancyIndicator")', function() {
      // uncomment below and update the code to test the property atcDiscrepancyIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property atcDiscrepancyValue (base name: "atcDiscrepancyValue")', function() {
      // uncomment below and update the code to test the property atcDiscrepancyValue
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property atcValue (base name: "atcValue")', function() {
      // uncomment below and update the code to test the property atcValue
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property authenticationIndicator (base name: "authenticationIndicator")', function() {
      // uncomment below and update the code to test the property authenticationIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property authorizationIdResponse (base name: "authorizationIdResponse")', function() {
      // uncomment below and update the code to test the property authorizationIdResponse
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property banknetDate (base name: "banknetDate")', function() {
      // uncomment below and update the code to test the property banknetDate
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property banknetReferenceNumber (base name: "banknetReferenceNumber")', function() {
      // uncomment below and update the code to test the property banknetReferenceNumber
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property billingCurrencyCode (base name: "billingCurrencyCode")', function() {
      // uncomment below and update the code to test the property billingCurrencyCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorCity (base name: "cardAcceptorCity")', function() {
      // uncomment below and update the code to test the property cardAcceptorCity
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorId (base name: "cardAcceptorId")', function() {
      // uncomment below and update the code to test the property cardAcceptorId
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorName (base name: "cardAcceptorName")', function() {
      // uncomment below and update the code to test the property cardAcceptorName
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorState (base name: "cardAcceptorState")', function() {
      // uncomment below and update the code to test the property cardAcceptorState
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorTerminalId (base name: "cardAcceptorTerminalId")', function() {
      // uncomment below and update the code to test the property cardAcceptorTerminalId
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderActivatedTerminalLevel (base name: "cardholderActivatedTerminalLevel")', function() {
      // uncomment below and update the code to test the property cardholderActivatedTerminalLevel
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderBillingActualAmount (base name: "cardholderBillingActualAmount")', function() {
      // uncomment below and update the code to test the property cardholderBillingActualAmount
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderBillingAmount (base name: "cardholderBillingAmount")', function() {
      // uncomment below and update the code to test the property cardholderBillingAmount
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAuthenticationMethodValidationCode (base name: "cardAuthenticationMethodValidationCode")', function() {
      // uncomment below and update the code to test the property cardAuthenticationMethodValidationCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property conversionDate (base name: "conversionDate")', function() {
      // uncomment below and update the code to test the property conversionDate
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property conversionRate (base name: "conversionRate")', function() {
      // uncomment below and update the code to test the property conversionRate
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property electronicCommerceIndicators (base name: "electronicCommerceIndicators")', function() {
      // uncomment below and update the code to test the property electronicCommerceIndicators
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property electronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator (base name: "electronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator")', function() {
      // uncomment below and update the code to test the property electronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property expirationDatePresenceInd (base name: "expirationDatePresenceInd")', function() {
      // uncomment below and update the code to test the property expirationDatePresenceInd
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property finalAuthorizationIndicator (base name: "finalAuthorizationIndicator")', function() {
      // uncomment below and update the code to test the property finalAuthorizationIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property financialNetworkCode (base name: "financialNetworkCode")', function() {
      // uncomment below and update the code to test the property financialNetworkCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property forwardingInstitutionId (base name: "forwardingInstitutionId")', function() {
      // uncomment below and update the code to test the property forwardingInstitutionId
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property infData (base name: "infData")', function() {
      // uncomment below and update the code to test the property infData
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property integratedCircuitCardRelatedData (base name: "integratedCircuitCardRelatedData")', function() {
      // uncomment below and update the code to test the property integratedCircuitCardRelatedData
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property issuer (base name: "issuer")', function() {
      // uncomment below and update the code to test the property issuer
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property mastercardPromotionCode (base name: "mastercardPromotionCode")', function() {
      // uncomment below and update the code to test the property mastercardPromotionCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property mccMessageId (base name: "mccMessageId")', function() {
      // uncomment below and update the code to test the property mccMessageId
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property merchantAdviceCode (base name: "merchantAdviceCode")', function() {
      // uncomment below and update the code to test the property merchantAdviceCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property merchantCategoryCode (base name: "merchantCategoryCode")', function() {
      // uncomment below and update the code to test the property merchantCategoryCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property mobilePhoneNumber (base name: "mobilePhoneNumber")', function() {
      // uncomment below and update the code to test the property mobilePhoneNumber
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property mobilePhoneServiceProviderName (base name: "mobilePhoneServiceProviderName")', function() {
      // uncomment below and update the code to test the property mobilePhoneServiceProviderName
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property originalAcquiringInstitutionIdCode (base name: "originalAcquiringInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property originalAcquiringInstitutionIdCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property originalElectronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator (base name: "originalElectronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator")', function() {
      // uncomment below and update the code to test the property originalElectronicCommerceSecurityLevelIndicatorAndUcafCollectionIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property originalIssuerForwardingInstitutionIdCode (base name: "originalIssuerForwardingInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property originalIssuerForwardingInstitutionIdCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property originalMessageTypeIdentifier (base name: "originalMessageTypeIdentifier")', function() {
      // uncomment below and update the code to test the property originalMessageTypeIdentifier
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property pinServiceCode (base name: "pinServiceCode")', function() {
      // uncomment below and update the code to test the property pinServiceCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property realTimeSubstantiationIndicator (base name: "realTimeSubstantiationIndicator")', function() {
      // uncomment below and update the code to test the property realTimeSubstantiationIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property reasonForUcafCollectionIndicatorDowngrade (base name: "reasonForUcafCollectionIndicatorDowngrade")', function() {
      // uncomment below and update the code to test the property reasonForUcafCollectionIndicatorDowngrade
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posCardDataTerminalInputCapability (base name: "posCardDataTerminalInputCapability")', function() {
      // uncomment below and update the code to test the property posCardDataTerminalInputCapability
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posCardholderPresence (base name: "posCardholderPresence")', function() {
      // uncomment below and update the code to test the property posCardholderPresence
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posCardPresence (base name: "posCardPresence")', function() {
      // uncomment below and update the code to test the property posCardPresence
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posEntryModePan (base name: "posEntryModePan")', function() {
      // uncomment below and update the code to test the property posEntryModePan
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posEntryModePin (base name: "posEntryModePin")', function() {
      // uncomment below and update the code to test the property posEntryModePin
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posTerminalAttendance (base name: "posTerminalAttendance")', function() {
      // uncomment below and update the code to test the property posTerminalAttendance
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posTerminalLocation (base name: "posTerminalLocation")', function() {
      // uncomment below and update the code to test the property posTerminalLocation
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property posTransactionStatus (base name: "posTransactionStatus")', function() {
      // uncomment below and update the code to test the property posTransactionStatus
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property primaryAccountNumber (base name: "primaryAccountNumber")', function() {
      // uncomment below and update the code to test the property primaryAccountNumber
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property primaryAccountNumberAccountRange (base name: "primaryAccountNumberAccountRange")', function() {
      // uncomment below and update the code to test the property primaryAccountNumberAccountRange
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property privateData (base name: "privateData")', function() {
      // uncomment below and update the code to test the property privateData
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property processingCode (base name: "processingCode")', function() {
      // uncomment below and update the code to test the property processingCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property recordDataPresenceIndicator (base name: "recordDataPresenceIndicator")', function() {
      // uncomment below and update the code to test the property recordDataPresenceIndicator
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property responseCode (base name: "responseCode")', function() {
      // uncomment below and update the code to test the property responseCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property retrievalReferenceNumber (base name: "retrievalReferenceNumber")', function() {
      // uncomment below and update the code to test the property retrievalReferenceNumber
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property settlementActualAmount (base name: "settlementActualAmount")', function() {
      // uncomment below and update the code to test the property settlementActualAmount
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property settlementDate (base name: "settlementDate")', function() {
      // uncomment below and update the code to test the property settlementDate
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property stan (base name: "stan")', function() {
      // uncomment below and update the code to test the property stan
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property storageTechnology (base name: "storageTechnology")', function() {
      // uncomment below and update the code to test the property storageTechnology
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property systemsTraceAuditNumber (base name: "systemsTraceAuditNumber")', function() {
      // uncomment below and update the code to test the property systemsTraceAuditNumber
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property tokenAssuranceLevel (base name: "tokenAssuranceLevel")', function() {
      // uncomment below and update the code to test the property tokenAssuranceLevel
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property tokenRequestorId (base name: "tokenRequestorId")', function() {
      // uncomment below and update the code to test the property tokenRequestorId
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property track1 (base name: "track1")', function() {
      // uncomment below and update the code to test the property track1
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property track2 (base name: "track2")', function() {
      // uncomment below and update the code to test the property track2
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionActualAmount (base name: "transactionActualAmount")', function() {
      // uncomment below and update the code to test the property transactionActualAmount
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionAmountLocal (base name: "transactionAmountLocal")', function() {
      // uncomment below and update the code to test the property transactionAmountLocal
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionCategoryCode (base name: "transactionCategoryCode")', function() {
      // uncomment below and update the code to test the property transactionCategoryCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionCurrencyCode (base name: "transactionCurrencyCode")', function() {
      // uncomment below and update the code to test the property transactionCurrencyCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionType (base name: "transactionType")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property transmissionDateAndTime (base name: "transmissionDateAndTime")', function() {
      // uncomment below and update the code to test the property transmissionDateAndTime
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property universalCardholderAuthenticationFieldUcaf (base name: "universalCardholderAuthenticationFieldUcaf")', function() {
      // uncomment below and update the code to test the property universalCardholderAuthenticationFieldUcaf
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property vcnProductCode (base name: "vcnProductCode")', function() {
      // uncomment below and update the code to test the property vcnProductCode
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

    it('should have the property walletIdentifier (base name: "walletIdentifier")', function() {
      // uncomment below and update the code to test the property walletIdentifier
      //var instance = new MasterCom.AuthorizationDetail();
      //expect(instance).to.be();
    });

  });

}));
