/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.CaseFilingDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CaseFilingDetails', function() {
    it('should create an instance of CaseFilingDetails', function() {
      // uncomment below and update the code to test CaseFilingDetails
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be.a(MasterCom.CaseFilingDetails);
    });

    it('should have the property claimId (base name: "claimId")', function() {
      // uncomment below and update the code to test the property claimId
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property claimType (base name: "claimType")', function() {
      // uncomment below and update the code to test the property claimType
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property caseId (base name: "caseId")', function() {
      // uncomment below and update the code to test the property caseId
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property caseType (base name: "caseType")', function() {
      // uncomment below and update the code to test the property caseType
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property chargebackRefNum (base name: "chargebackRefNum")', function() {
      // uncomment below and update the code to test the property chargebackRefNum
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currencyCode")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property customerFilingNumber (base name: "customerFilingNumber")', function() {
      // uncomment below and update the code to test the property customerFilingNumber
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property creditDate (base name: "creditDate")', function() {
      // uncomment below and update the code to test the property creditDate
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property chargebackDate (base name: "chargebackDate")', function() {
      // uncomment below and update the code to test the property chargebackDate
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property reasonCode (base name: "reasonCode")', function() {
      // uncomment below and update the code to test the property reasonCode
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property disputeAmount (base name: "disputeAmount")', function() {
      // uncomment below and update the code to test the property disputeAmount
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property dueDate (base name: "dueDate")', function() {
      // uncomment below and update the code to test the property dueDate
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property filingAgaintstIca (base name: "filingAgaintstIca")', function() {
      // uncomment below and update the code to test the property filingAgaintstIca
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property filingAs (base name: "filingAs")', function() {
      // uncomment below and update the code to test the property filingAs
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property filingIca (base name: "filingIca")', function() {
      // uncomment below and update the code to test the property filingIca
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property merchantName (base name: "merchantName")', function() {
      // uncomment below and update the code to test the property merchantName
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property primaryAccountNum (base name: "primaryAccountNum")', function() {
      // uncomment below and update the code to test the property primaryAccountNum
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property violationCode (base name: "violationCode")', function() {
      // uncomment below and update the code to test the property violationCode
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property violationDate (base name: "violationDate")', function() {
      // uncomment below and update the code to test the property violationDate
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property rulingDate (base name: "rulingDate")', function() {
      // uncomment below and update the code to test the property rulingDate
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property rulingStatus (base name: "rulingStatus")', function() {
      // uncomment below and update the code to test the property rulingStatus
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

    it('should have the property virtualAccountNum (base name: "virtualAccountNum")', function() {
      // uncomment below and update the code to test the property virtualAccountNum
      //var instance = new MasterCom.CaseFilingDetails();
      //expect(instance).to.be();
    });

  });

}));
