/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.ClearingDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClearingDetail', function() {
    it('should create an instance of ClearingDetail', function() {
      // uncomment below and update the code to test ClearingDetail
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be.a(MasterCom.ClearingDetail);
    });

    it('should have the property accountLevelManagementAccountCategoryCode (base name: "accountLevelManagementAccountCategoryCode")', function() {
      // uncomment below and update the code to test the property accountLevelManagementAccountCategoryCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquirerReferenceData (base name: "acquirerReferenceData")', function() {
      // uncomment below and update the code to test the property acquirerReferenceData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquiringInstitutionIdCode (base name: "acquiringInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property acquiringInstitutionIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property approvalCode (base name: "approvalCode")', function() {
      // uncomment below and update the code to test the property approvalCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property businessCycle (base name: "businessCycle")', function() {
      // uncomment below and update the code to test the property businessCycle
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property businessServiceArrangementTypeCode (base name: "businessServiceArrangementTypeCode")', function() {
      // uncomment below and update the code to test the property businessServiceArrangementTypeCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property businessServiceIdCode (base name: "businessServiceIdCode")', function() {
      // uncomment below and update the code to test the property businessServiceIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorBusinessCode (base name: "cardAcceptorBusinessCode")', function() {
      // uncomment below and update the code to test the property cardAcceptorBusinessCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorCity (base name: "cardAcceptorCity")', function() {
      // uncomment below and update the code to test the property cardAcceptorCity
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorClassificationOverrideIndicator (base name: "cardAcceptorClassificationOverrideIndicator")', function() {
      // uncomment below and update the code to test the property cardAcceptorClassificationOverrideIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorCountry (base name: "cardAcceptorCountry")', function() {
      // uncomment below and update the code to test the property cardAcceptorCountry
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorIdCode (base name: "cardAcceptorIdCode")', function() {
      // uncomment below and update the code to test the property cardAcceptorIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorName (base name: "cardAcceptorName")', function() {
      // uncomment below and update the code to test the property cardAcceptorName
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorPostalCode (base name: "cardAcceptorPostalCode")', function() {
      // uncomment below and update the code to test the property cardAcceptorPostalCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorState (base name: "cardAcceptorState")', function() {
      // uncomment below and update the code to test the property cardAcceptorState
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorStreetAddress (base name: "cardAcceptorStreetAddress")', function() {
      // uncomment below and update the code to test the property cardAcceptorStreetAddress
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorTerminalId (base name: "cardAcceptorTerminalId")', function() {
      // uncomment below and update the code to test the property cardAcceptorTerminalId
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardAcceptorUrl (base name: "cardAcceptorUrl")', function() {
      // uncomment below and update the code to test the property cardAcceptorUrl
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardCaptureCapability (base name: "cardCaptureCapability")', function() {
      // uncomment below and update the code to test the property cardCaptureCapability
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardDataInputCapability (base name: "cardDataInputCapability")', function() {
      // uncomment below and update the code to test the property cardDataInputCapability
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardDataInputMode (base name: "cardDataInputMode")', function() {
      // uncomment below and update the code to test the property cardDataInputMode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardDataOutputCapability (base name: "cardDataOutputCapability")', function() {
      // uncomment below and update the code to test the property cardDataOutputCapability
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderAuthenticationCapability (base name: "cardholderAuthenticationCapability")', function() {
      // uncomment below and update the code to test the property cardholderAuthenticationCapability
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderAuthenticationEntity (base name: "cardholderAuthenticationEntity")', function() {
      // uncomment below and update the code to test the property cardholderAuthenticationEntity
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderAuthenticationMethod (base name: "cardholderAuthenticationMethod")', function() {
      // uncomment below and update the code to test the property cardholderAuthenticationMethod
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderBillingAmount (base name: "cardholderBillingAmount")', function() {
      // uncomment below and update the code to test the property cardholderBillingAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderBillingCurrencyCode (base name: "cardholderBillingCurrencyCode")', function() {
      // uncomment below and update the code to test the property cardholderBillingCurrencyCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderFromAccountCode (base name: "cardholderFromAccountCode")', function() {
      // uncomment below and update the code to test the property cardholderFromAccountCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderPresentData (base name: "cardholderPresentData")', function() {
      // uncomment below and update the code to test the property cardholderPresentData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardholderToAccountCode (base name: "cardholderToAccountCode")', function() {
      // uncomment below and update the code to test the property cardholderToAccountCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardIssuerReferenceData (base name: "cardIssuerReferenceData")', function() {
      // uncomment below and update the code to test the property cardIssuerReferenceData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardPresentData (base name: "cardPresentData")', function() {
      // uncomment below and update the code to test the property cardPresentData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property cardProgramIdentifier (base name: "cardProgramIdentifier")', function() {
      // uncomment below and update the code to test the property cardProgramIdentifier
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property centralSiteBusinessDate (base name: "centralSiteBusinessDate")', function() {
      // uncomment below and update the code to test the property centralSiteBusinessDate
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property centralSiteProcessingDateOriginalMessage (base name: "centralSiteProcessingDateOriginalMessage")', function() {
      // uncomment below and update the code to test the property centralSiteProcessingDateOriginalMessage
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyCodeCardholderBilling (base name: "currencyCodeCardholderBilling")', function() {
      // uncomment below and update the code to test the property currencyCodeCardholderBilling
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyCodeReconciliation (base name: "currencyCodeReconciliation")', function() {
      // uncomment below and update the code to test the property currencyCodeReconciliation
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyCodeTransaction (base name: "currencyCodeTransaction")', function() {
      // uncomment below and update the code to test the property currencyCodeTransaction
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyExponentCardholderBilling (base name: "currencyExponentCardholderBilling")', function() {
      // uncomment below and update the code to test the property currencyExponentCardholderBilling
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyExponentReconciliation (base name: "currencyExponentReconciliation")', function() {
      // uncomment below and update the code to test the property currencyExponentReconciliation
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyExponentTransaction (base name: "currencyExponentTransaction")', function() {
      // uncomment below and update the code to test the property currencyExponentTransaction
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property dataRecord (base name: "dataRecord")', function() {
      // uncomment below and update the code to test the property dataRecord
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property electronicCommerceCardAuth (base name: "electronicCommerceCardAuth")', function() {
      // uncomment below and update the code to test the property electronicCommerceCardAuth
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property electronicCommerceSecurityLevelIndicator (base name: "electronicCommerceSecurityLevelIndicator")', function() {
      // uncomment below and update the code to test the property electronicCommerceSecurityLevelIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property electronicCommerceUcafCollectionIndicator (base name: "electronicCommerceUcafCollectionIndicator")', function() {
      // uncomment below and update the code to test the property electronicCommerceUcafCollectionIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property forwardingInstitutionIdCode (base name: "forwardingInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property forwardingInstitutionIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentAmount (base name: "installmentAmount")', function() {
      // uncomment below and update the code to test the property installmentAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentFee (base name: "installmentFee")', function() {
      // uncomment below and update the code to test the property installmentFee
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentNumber (base name: "installmentNumber")', function() {
      // uncomment below and update the code to test the property installmentNumber
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataBrazil (base name: "installmentPaymentDataBrazil")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataBrazil
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property additionalAmountDataCode (base name: "additionalAmountDataCode")', function() {
      // uncomment below and update the code to test the property additionalAmountDataCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentParameters (base name: "installmentParameters")', function() {
      // uncomment below and update the code to test the property installmentParameters
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property originalInformationInstallments (base name: "originalInformationInstallments")', function() {
      // uncomment below and update the code to test the property originalInformationInstallments
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPlanType (base name: "installmentPlanType")', function() {
      // uncomment below and update the code to test the property installmentPlanType
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property functionCode (base name: "functionCode")', function() {
      // uncomment below and update the code to test the property functionCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property gcmsProductIndentifier (base name: "gcmsProductIndentifier")', function() {
      // uncomment below and update the code to test the property gcmsProductIndentifier
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentData (base name: "installmentPaymentData")', function() {
      // uncomment below and update the code to test the property installmentPaymentData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataAnnualPercentageRate (base name: "installmentPaymentDataAnnualPercentageRate")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataAnnualPercentageRate
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataFirstInstallmentAmount (base name: "installmentPaymentDataFirstInstallmentAmount")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataFirstInstallmentAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataInstallmentFee (base name: "installmentPaymentDataInstallmentFee")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataInstallmentFee
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataInterestRate (base name: "installmentPaymentDataInterestRate")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataInterestRate
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataNumberInstallments (base name: "installmentPaymentDataNumberInstallments")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataNumberInstallments
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentPaymentDataSubsequentInstallmentAmount (base name: "installmentPaymentDataSubsequentInstallmentAmount")', function() {
      // uncomment below and update the code to test the property installmentPaymentDataSubsequentInstallmentAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property integratedCircuitCardRelatedData (base name: "integratedCircuitCardRelatedData")', function() {
      // uncomment below and update the code to test the property integratedCircuitCardRelatedData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property interchangeRateDesignator (base name: "interchangeRateDesignator")', function() {
      // uncomment below and update the code to test the property interchangeRateDesignator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property licensedProductIndentifier (base name: "licensedProductIndentifier")', function() {
      // uncomment below and update the code to test the property licensedProductIndentifier
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property legalCorporateName (base name: "legalCorporateName")', function() {
      // uncomment below and update the code to test the property legalCorporateName
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property localMessageReasonCode (base name: "localMessageReasonCode")', function() {
      // uncomment below and update the code to test the property localMessageReasonCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property localTax1IVA (base name: "localTax1IVA")', function() {
      // uncomment below and update the code to test the property localTax1IVA
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property localTransactionDateTime (base name: "localTransactionDateTime")', function() {
      // uncomment below and update the code to test the property localTransactionDateTime
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property mastercardAssignedId (base name: "mastercardAssignedId")', function() {
      // uncomment below and update the code to test the property mastercardAssignedId
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property mastercardAssignedIdOverrideIndicator (base name: "mastercardAssignedIdOverrideIndicator")', function() {
      // uncomment below and update the code to test the property mastercardAssignedIdOverrideIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property mastercardMappingServiceAccountNumber (base name: "mastercardMappingServiceAccountNumber")', function() {
      // uncomment below and update the code to test the property mastercardMappingServiceAccountNumber
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property masterPassIncentiveIndicator (base name: "masterPassIncentiveIndicator")', function() {
      // uncomment below and update the code to test the property masterPassIncentiveIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property messageReasonCode (base name: "messageReasonCode")', function() {
      // uncomment below and update the code to test the property messageReasonCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property messageReversalIndicator (base name: "messageReversalIndicator")', function() {
      // uncomment below and update the code to test the property messageReversalIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property numberOfInstallments (base name: "numberOfInstallments")', function() {
      // uncomment below and update the code to test the property numberOfInstallments
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property originatingMessageFormat (base name: "originatingMessageFormat")', function() {
      // uncomment below and update the code to test the property originatingMessageFormat
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property partnerIdCode (base name: "partnerIdCode")', function() {
      // uncomment below and update the code to test the property partnerIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property pinCaptureCapability (base name: "pinCaptureCapability")', function() {
      // uncomment below and update the code to test the property pinCaptureCapability
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property primaryAccountNumber (base name: "primaryAccountNumber")', function() {
      // uncomment below and update the code to test the property primaryAccountNumber
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property processingCode (base name: "processingCode")', function() {
      // uncomment below and update the code to test the property processingCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property productOverrideIndicator (base name: "productOverrideIndicator")', function() {
      // uncomment below and update the code to test the property productOverrideIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property programRegistrationId (base name: "programRegistrationId")', function() {
      // uncomment below and update the code to test the property programRegistrationId
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property qpsPaypassEligibilityIndicator (base name: "qpsPaypassEligibilityIndicator")', function() {
      // uncomment below and update the code to test the property qpsPaypassEligibilityIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property rateIndicator (base name: "rateIndicator")', function() {
      // uncomment below and update the code to test the property rateIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property receivingInstitutionIdCode (base name: "receivingInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property receivingInstitutionIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property reconciliationAmount (base name: "reconciliationAmount")', function() {
      // uncomment below and update the code to test the property reconciliationAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property reconciliationCurrencyCode (base name: "reconciliationCurrencyCode")', function() {
      // uncomment below and update the code to test the property reconciliationCurrencyCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property remotePaymentsProgramData (base name: "remotePaymentsProgramData")', function() {
      // uncomment below and update the code to test the property remotePaymentsProgramData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property serviceCode (base name: "serviceCode")', function() {
      // uncomment below and update the code to test the property serviceCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property settlementData (base name: "settlementData")', function() {
      // uncomment below and update the code to test the property settlementData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property settlementIndicator (base name: "settlementIndicator")', function() {
      // uncomment below and update the code to test the property settlementIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property specialConditionsIndicator (base name: "specialConditionsIndicator")', function() {
      // uncomment below and update the code to test the property specialConditionsIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property terminalDataOutputCapability (base name: "terminalDataOutputCapability")', function() {
      // uncomment below and update the code to test the property terminalDataOutputCapability
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property terminalOperatingEnvironment (base name: "terminalOperatingEnvironment")', function() {
      // uncomment below and update the code to test the property terminalOperatingEnvironment
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property terminalType (base name: "terminalType")', function() {
      // uncomment below and update the code to test the property terminalType
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property tokenRequestorId (base name: "tokenRequestorId")', function() {
      // uncomment below and update the code to test the property tokenRequestorId
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property totalTransactionAmount (base name: "totalTransactionAmount")', function() {
      // uncomment below and update the code to test the property totalTransactionAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionAmountLocal (base name: "transactionAmountLocal")', function() {
      // uncomment below and update the code to test the property transactionAmountLocal
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionCategoryIndicator (base name: "transactionCategoryIndicator")', function() {
      // uncomment below and update the code to test the property transactionCategoryIndicator
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionCurrencyCode (base name: "transactionCurrencyCode")', function() {
      // uncomment below and update the code to test the property transactionCurrencyCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionDestinationInstitutionIdCode (base name: "transactionDestinationInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property transactionDestinationInstitutionIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionLifeCycleId (base name: "transactionLifeCycleId")', function() {
      // uncomment below and update the code to test the property transactionLifeCycleId
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionOriginatorInstitutionIdCode (base name: "transactionOriginatorInstitutionIdCode")', function() {
      // uncomment below and update the code to test the property transactionOriginatorInstitutionIdCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transactionType (base name: "transactionType")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property transitProgramCode (base name: "transitProgramCode")', function() {
      // uncomment below and update the code to test the property transitProgramCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property walletIdentifierMdes (base name: "walletIdentifierMdes")', function() {
      // uncomment below and update the code to test the property walletIdentifierMdes
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property currencyConversionAssessmentAmount (base name: "currencyConversionAssessmentAmount")', function() {
      // uncomment below and update the code to test the property currencyConversionAssessmentAmount
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property japanCommonMerchantCode (base name: "japanCommonMerchantCode")', function() {
      // uncomment below and update the code to test the property japanCommonMerchantCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property installmentData (base name: "installmentData")', function() {
      // uncomment below and update the code to test the property installmentData
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

    it('should have the property flexCode (base name: "flexCode")', function() {
      // uncomment below and update the code to test the property flexCode
      //var instance = new MasterCom.ClearingDetail();
      //expect(instance).to.be();
    });

  });

}));
