/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.CreateFeeRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateFeeRequest', function() {
    it('should create an instance of CreateFeeRequest', function() {
      // uncomment below and update the code to test CreateFeeRequest
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be.a(MasterCom.CreateFeeRequest);
    });

    it('should have the property cardAcceptorIdCode (base name: "cardAcceptorIdCode")', function() {
      // uncomment below and update the code to test the property cardAcceptorIdCode
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property cardNumber (base name: "cardNumber")', function() {
      // uncomment below and update the code to test the property cardNumber
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property feeDate (base name: "feeDate")', function() {
      // uncomment below and update the code to test the property feeDate
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property destinationMember (base name: "destinationMember")', function() {
      // uncomment below and update the code to test the property destinationMember
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property feeAmount (base name: "feeAmount")', function() {
      // uncomment below and update the code to test the property feeAmount
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property creditSender (base name: "creditSender")', function() {
      // uncomment below and update the code to test the property creditSender
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property creditReceiver (base name: "creditReceiver")', function() {
      // uncomment below and update the code to test the property creditReceiver
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property mastercomControlNumber (base name: "mastercomControlNumber")', function() {
      // uncomment below and update the code to test the property mastercomControlNumber
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property settlementDate (base name: "settlementDate")', function() {
      // uncomment below and update the code to test the property settlementDate
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property replyFeeId (base name: "replyFeeId")', function() {
      // uncomment below and update the code to test the property replyFeeId
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

    it('should have the property feeType (base name: "feeType")', function() {
      // uncomment below and update the code to test the property feeType
      //var instance = new MasterCom.CreateFeeRequest();
      //expect(instance).to.be();
    });

  });

}));
