/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.CreateClaimRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateClaimRequest', function() {
    it('should create an instance of CreateClaimRequest', function() {
      // uncomment below and update the code to test CreateClaimRequest
      //var instance = new MasterCom.CreateClaimRequest();
      //expect(instance).to.be.a(MasterCom.CreateClaimRequest);
    });

    it('should have the property disputedAmount (base name: "disputedAmount")', function() {
      // uncomment below and update the code to test the property disputedAmount
      //var instance = new MasterCom.CreateClaimRequest();
      //expect(instance).to.be();
    });

    it('should have the property disputedCurrency (base name: "disputedCurrency")', function() {
      // uncomment below and update the code to test the property disputedCurrency
      //var instance = new MasterCom.CreateClaimRequest();
      //expect(instance).to.be();
    });

    it('should have the property claimType (base name: "claimType")', function() {
      // uncomment below and update the code to test the property claimType
      //var instance = new MasterCom.CreateClaimRequest();
      //expect(instance).to.be();
    });

    it('should have the property clearingTransactionId (base name: "clearingTransactionId")', function() {
      // uncomment below and update the code to test the property clearingTransactionId
      //var instance = new MasterCom.CreateClaimRequest();
      //expect(instance).to.be();
    });

    it('should have the property authTransactionId (base name: "authTransactionId")', function() {
      // uncomment below and update the code to test the property authTransactionId
      //var instance = new MasterCom.CreateClaimRequest();
      //expect(instance).to.be();
    });

  });

}));
