/**
 * MasterCom
 * MasterCom
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MasterCom);
  }
}(this, function(expect, MasterCom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MasterCom.CreateFraudMasterCardRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateFraudMasterCardRequest', function() {
    it('should create an instance of CreateFraudMasterCardRequest', function() {
      // uncomment below and update the code to test CreateFraudMasterCardRequest
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be.a(MasterCom.CreateFraudMasterCardRequest);
    });

    it('should have the property acctStatus (base name: "acctStatus")', function() {
      // uncomment below and update the code to test the property acctStatus
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

    it('should have the property chgbkIndicator (base name: "chgbkIndicator")', function() {
      // uncomment below and update the code to test the property chgbkIndicator
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

    it('should have the property cvcInvalidIndicator (base name: "cvcInvalidIndicator")', function() {
      // uncomment below and update the code to test the property cvcInvalidIndicator
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

    it('should have the property deviceType (base name: "deviceType")', function() {
      // uncomment below and update the code to test the property deviceType
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

    it('should have the property fraudType (base name: "fraudType")', function() {
      // uncomment below and update the code to test the property fraudType
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

    it('should have the property reportDate (base name: "reportDate")', function() {
      // uncomment below and update the code to test the property reportDate
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

    it('should have the property subType (base name: "subType")', function() {
      // uncomment below and update the code to test the property subType
      //var instance = new MasterCom.CreateFraudMasterCardRequest();
      //expect(instance).to.be();
    });

  });

}));
